[[schemas]]
[appendix]
:appendix-caption: Annex
== Schemas (Normative)

NOTE: The JSON-FG Schema documents will only be published in the https://schemas.opengis.net/[OGC Schema Repository], if and once the JSON-FG Standard has been approved. Until then, the schema documents will be made available in the https://beta.schemas.opengis.net/[OGC Schema Repository for drafts]. This note will be removed before publishing the JSON-FG Standard.

[[schema-jsonfg-root-object]]
=== JSON Schema of a JSON-FG root object

[source,json,linenumbers]
----
include::schemas/jsonfg-root-object.json[]
----

[[schema-feature-collection]]
=== JSON Schema of a JSON-FG feature collection 

[source,json,linenumbers]
----
include::schemas/featurecollection.json[]
----

[[schema-feature]]
=== JSON Schema of a JSON-FG feature 

[source,json,linenumbers]
----
include::schemas/feature.json[]
----

[[schema-geometry-object]]
=== JSON Schema of a JSON-FG geometry

[source,json,linenumbers]
----
include::schemas/geometry-object.json[]
----

[[schema-conformsto]]
=== JSON Schema of the "conformsTo" member

[source,json,linenumbers]
----
include::schemas/conformsto.json[]
----

[[schema-time]]
=== JSON Schema of the "time" member

[source,json,linenumbers]
----
include::schemas/time.json[]
----

[[schema-place]]
=== JSON Schema of the "place" member

[source,json,linenumbers]
----
include::schemas/place.json[]
----

[[schema-coordrefsys]]
=== JSON Schema of the "coordRefSys" member

[source,json,linenumbers]
----
include::schemas/coordrefsys.json[]
----

[[schema-measures]]
=== JSON Schema of the "measures" member

[source,json,linenumbers]
----
include::schemas/measures.json[]
----

[[schema-geometry]]
=== JSON Schema of the "geometry" member

[source,json,linenumbers]
----
include::schemas/geometry.json[]
----

[[schema-featuretype]]
=== JSON Schema of the "featureType" member

[source,json,linenumbers]
----
include::schemas/featuretype.json[]
----

[[schema-featureschema]]
=== JSON Schema of the "featureSchema" member

[source,json,linenumbers]
----
include::schemas/featureschema.json[]
----


