[[relationships_and_links]]
[appendix]
:appendix-caption: Annex
== Links (Informative)

There are multiple ways how to encode feature properties that are relationships with other features or resources like codelists and where the value is not embedded, but represented as a link. This annex discusses the topic.

=== A sample feature

In this annex a cadastral parcel feature is used as the sample feature resource. The hypothetical parcel has the following properties: 

* a (multi-)polygon geometry (ignored in the JSON examples to keep the examples short);
* a parcel identifier ("foo");
* its area (2000 square meters);
* a set of ownership records (two owners, each with 50% share);
* a set of buildings on the parcel (one building on the parcel);
* information about land use (using a national classification system) and the area for each applicable land use type (500 square meters with residential use, 1500 square meters with commercial use).

The owners, buildings and land use types are web resources, too, and have URIs as identifiers.

=== Scope discussion

The related resources can be referenced or embedded in the feature representation (embedding is only sensible, if the resource can be represented as a JSON object). This proposal only discusses the case where a related resource is referenced and where the related resources are web resources, i.e. resources that are identified by HTTP(S) URIs. If resources are embedded, they will be embedded as a value in a member in the "properties" object.

Relationships will often be direct properties of the feature, but they may also occur in embedded JSON objects.

Like all other properties, properties that are relationships may have a maximum multiplicity greater than one. That is, the JSON representation may be an array of relationships.

A GeoJSON feature that is encoded by a Web API implementing OGC API standards will often already include a "links" member with an array of OGC API Link objects. The OGC API Link object is a JSON implementation of web links according to RFC 8288. As discussed above, the OGC API Features standard currently only specifies requirements for links to resources in the API to support clients navigating the API.

=== Patterns

Three patterns for representing relationships with other features or resources are discussed below. They all address different use cases.

==== Pattern 1: Add all relationships to a "links" member of the JSON object that is the link anchor

This pattern is consistent with the general approach in the OGC API standards. It uses Web linking and a consistently named JSON member with an array of OGC API Link objects.

The semantics of the relationship / association role is expressed via the link relation type. Where possible, link relation types registered with IANA or OGC should be used, but the data publisher can also define their own link relation types. Note that this introduces overhead, because it requires minting persistent URIs for the link relation types. Where this is too much, an existing link relation type should be used and "related" could be used as a fallback.

Note that the examples use https://www.w3.org/TR/curie/[Safe CURIEs] for better readability in cases where the link relation type is a URI.

The parcel feature could looks like the following example, which uses the "anchor" link attribute to specify the link context. The building relationship has been mapped to a hypothetical "http://www.opengis.net/def/rel/ogc/1.0/contains" link relationship based on the topological relationship "contains" from the Simple Features standard.

NOTE: #Link relation types for the topological interval relationships as specified in OWL Time are already registered with IANA. The registration of the named spatial topological relationships specified in the Simple Feature Access standard cite:[OGC06_103r4] should be considered, either in the IANA or the OGC register. Such link relation types are useful for cases where relationships are pre-computed or are computed on the fly but are presented, because the clients cannot easily compute them.#

[source,json,linenumbers]
----
{
   "type":"Feature",
   "geometry": null,
   "links" : [ { 
      "title" : "123 Main St., Atlantis",
      "href" : "https://example.com/building/123",
      "rel" : "[ogc:contains]"
   }, {
      "anchor": "#/properties/owners/0", 
      "href": "https://example.com/person/foo", 
      "title": "John Doe", 
      "rel": "[app:owner]" 
   }, {
      "anchor": "#/properties/owners/1", 
      "href": "https://example.com/company/bar", 
      "title": "Acme Inc", 
      "rel": "[app:owner]" 
   }, {
      "anchor": "#/properties/landUse/0", 
      "href": "https://example.com/landuse/residential", 
      "title": "residential use", 
      "rel": "[app:land-use]" 
   }, {
      "anchor": "#/properties/landUse/1", 
      "href": "https://example.com/landuse/commercial", 
      "title": "commercial use", 
      "rel": "[app:land-use]" 
   } ],
   "properties": {
      "registerId": "foo",
      "area_m2": 2000,
      "owners": [ 
         { "share_%": 50 },
         { "share_%": 50 } 
      ],
      "use": [ 
         { "area_m2": 500 },
         { "area_m2": 1500 }
      ]
   }
}
----

A variation of this approach would be to separate the API navigation links ("links") from the feature properties and place those links in another member (e.g. "associations").

Another variation would be to not use anchors, but specify the links in JSON object that is the link context:

[source,json,linenumbers]
----
{
   "type":"Feature",
   "geometry": null,
   "links" : [ { 
      "rel" : "[contains]",
      "title" : "123 Main St., Atlantis",
      "href" : "https://example.com/building/123"
   } ],
   "properties": {
      "registerId": "foo",
      "area_m2": 2000,
      "owners": [ {
         "share_%": 50,
         "links": [ { 
            "href": "https://example.com/person/foo", 
            "title": "John Doe", 
            "rel": "[app:owner]" 
         } ],
      }, {
        "share_%": 50,
         "links": [ { 
            "href": "https://example.com/company/bar", 
            "title": "Acme Inc", 
            "rel": "[app:owner]" 
         } ],
      } ],
      "use": [ {
         "area_m2": 500,
         "links": [ { 
            "href": "https://example.com/landuse/residential", 
            "title": "residential use", 
            "rel": "[app:land-use]" 
         } ]
      }, {
        "area_m2": 1500,
         "links": [ { 
            "href": "https://example.com/landuse/commercial", 
            "title": "commercial use", 
            "rel": "[app:land-use]" 
         } ]
      } ]
   }
}
----

==== Pattern 2: Encode links like other feature properties - using a link object

This pattern treats the relationships like other properties and uses a simplified OGC API Link object without a "rel" attribute, since the semantics of the link is already expressed by the property. 

A variation could be to require the use of a valid link relation type as the key of the JSON member, which would basically move the link relation type to a key to group all links with the same link relation type.

[source,json,linenumbers]
----

{
   "type":"Feature",
   "geometry": null,
   "properties": {
      "registerId": "foo",
      "area_m2": 2000,
      "buildings": [ {
         "title" : "123 Main St., Atlantis",
         "href" : "https://example.com/building/123"
      } ],
      "owners": [ {
         "share_%": 50,
         "owner": { 
            "href": "https://example.com/person/foo", 
            "title": "John Doe"
         }
      }, {
         "share_%": 50,
         "owner": { 
            "href": "https://example.com/company/bar", 
            "title": "Acme Inc"
         }
      } ],
      "use": [ {
         "area_m2": 500,
         "landUse": { 
            "href": "https://example.com/landuse/residential", 
            "title": "residential use"
         }
      }, {
         "area_m2": 1500,
         "landUse": { 
            "href": "https://example.com/landuse/commercial", 
            "title": "commercial use"
         }
      } ]
   }
}
----

A variation of this pattern would be to flatten the link objects. I.e., instead of

[source,json,linenumbers]
----
   "owner": { 
      "href": "https://example.com/company/bar", 
      "title": "Acme Inc"
   }
----

the link could be encoded as

[source,json,linenumbers]
----
   "owner.href": "https://example.com/company/bar", 
   "owner.title": "Acme Inc"
----

==== Pattern 3: Only use the URI

This pattern is similar to pattern 2, but the link objects are reduced to the href value. As a result, this approach is more concise, but it lacks information that would be useful for the human (unless the URIs are dereferenced to fetch a label/title). In addition, since this approach does not use web linking according to RFC 8288, no link relation types for the links are available.

[source,json,linenumbers]
----

{
   "type":"Feature",
   "geometry": null,
   "properties": {
      "registerId": "foo",
      "area_m2": 2000,
      "buildings": [ 
         "https://example.com/building/123"
      ],
      "owners": [ {
         "share_%": 50,
         "owner": "https://example.com/person/foo"
      }, {
         "share_%": 50,
         "owner": "https://example.com/company/bar"
      } ],
      "use": [ {
         "area_m2": 500,
         "landUse": "https://example.com/landuse/residential"
      }, {
         "area_m2": 1500,
         "landUse": "https://example.com/landuse/commercial"
      } ]
   }
}
----

=== Summary

Pattern 1 seems best suited, if the intended use of the data benefits from a consistent place where links are included in the JSON document.

Pattern 2 seems best suited, if the JSON features should closely reflect the application schema of the features (in case a schema is available).

The same also applies to pattern 3, but pattern 3 seems mainly useful in combination with JSON-LD. Also, the information is not sufficient to render a useful HTML representation from the JSON representation without fetching the linked resources.

Depending on the data and how the data is expected to be used, the preferences of data publishers for one or the other patterns will vary.
