[#examples]
[appendix]
:appendix-caption: Annex
== Examples (Informative)

=== A building feature

The following feature instance is an example of a building feature that includes severel new JSON-FG capabilities.

[#example_building,reftext='{listing-caption} {counter:listing-num}']
.Building with a polyhedron geometry and the polygon footprint
====
[source%unnumbered,json,linenumbers]
----
include::examples/building.json[]
----
====

=== A road segment feature with measure values

The following feature instance is an example of a road segment feature.

[#example_road_segment,reftext='{listing-caption} {counter:listing-num}']
.A road element with measure values
====
[source%unnumbered,json,linenumbers]
----
include::examples/road-segment.json[]
----
====

=== A circle geometry

The following feature instance is an example of a circle as a JSON-FG outside of a feature context.

[#example_circle_document,reftext='{listing-caption} {counter:listing-num}']
.A circle
====
[source%unnumbered,json,linenumbers]
----
include::examples/circle-document.json[]
----
====

=== Simple prism geometries

The following are simple examples of prism geometries in a feature. 

[#example_pylon,reftext='{listing-caption} {counter:listing-num}']
.A pylon as a entruded point
====
[source%unnumbered,json,linenumbers]
----
include::examples/pylon.json[]
----
====

[#example_fence,reftext='{listing-caption} {counter:listing-num}']
.A fence as an extruded line string
====
[source%unnumbered,json,linenumbers]
----
include::examples/fence.json[]
----
====

=== Toronto City Hall

The following object is a feature representing the Toronto City Hall with the geometry as a MultiPrism (extruded polygons).

[#example_tch,reftext='{listing-caption} {counter:listing-num}']
.Toronto City Hall with a prism geometry
====
[source%unnumbered,json,linenumbers]
----
include::examples/toronto-city-hall.json[]
----
====

[[example_cc]]
=== Cologne Cathedral

The file https://github.com/opengeospatial/ogc-feat-geo-json/blob/main/core/examples/cologne-cathedral.json[cologne-cathedral.json] is a JSON-FG feature collection that contains a CityGML building feature with 87 building part features representing the Cologne Cathedral in Level of Detail 2. Each building part has a Polyhedron geometry. The building part feature also contain additional geometries in the "properties" section. Due to the size of the example, it is not embedded, but referenced.

=== A homogeneous feature collection

The following feature collection consists of airport features from the Zoomstack dataset of Ordnance Survey Great Britain. All features have the same feature type ("Airport") with a point geometry (geometry dimension: 0).

The feature collection has been reduced to the first two and the last feature to reduce the size of the example.

[#example_airports,reftext='{listing-caption} {counter:listing-num}']
.Airports in Great Britain
====
[source%unnumbered,json,linenumbers]
----
include::examples/airports.json[]
----
====

[#extending_jsonfg]
=== Extending JSON-FG

This section illustrates how JSON-FG can be extended with 

* new geometry type "GeodesicString" for a geodesic curve;
* a new temporal data type for a time series;
* the capability to provide a coordinate reference system definition as a PROJJSON object.

If the extension would be specified in a hypothetical part 2 of JSON-FG, the extension could update the JSON Schema definitions as described in the following sub-sections.

If the same extensions are specified by a community, they would copy the relevant JSON-FG schemas and extend them as described in the sub-sections. Unchanged schemas like the JSON Schemas for the "geometry" and "featureType" members or for a link do not need to be copied and can reference the JSON-FG schemas.

[[geometry_type_geodesicstring]]
==== Geometry type "GeodesicString"

A GeoJSON LineString is a sequence of straight lines through two or more positions with the assumption that Euclidean geometry is used. That is, while GeoJSON uses geographic coordinates (longitude and latitude) on an ellipsoid, the path between two positions is computed in a Cartesian coordinate system - applying the Pseudo Plate Carrée projection. In other words, the path between two positions is a straight line in the Cartesian coordinate system, not the shortest path on the WGS 84 ellipsoid. 

To support geodesic curves on the reference ellipsoid, a new geometry type "GeodesicString" could be defined. The new geometry type would be a sequence of geodesic lines between two or more positions on the ellipsoid.

A GeodesicString requires that the coordinates are in a geographic coordinate reference system (CRS) with longitude and latitude as the horizontal coordinates. 

Geometrical computations of a GeodesicString - including computation of length or area - should be performed on the curved surface that approximates the earth's surface. Details are provided, for example, in the drafts of <<ogc20_070,Features and Geometry - Part 2: Metrics>>.

If the "bbox" member is provided, it will be the bounding box that contains all positions along the path of the geodesic string. That is, it will in general be larger than the bounding box of the positions in the "coordinates" member.

The schema definition for a new geometry "GeodesicString" shown below could be added as `\#/$defs/GeodesicString` in the JSON Schema of geometries ("geometry-object.json"). 

[source,json,linenumbers]
----
include::examples/extensions/geodesicstring.json[]
----

"GeodesicString" would also be added to `#/$defs/CustomGeometry/properties/type/not/enum` in "geometry-object.json" to declare the new JSON-FG geometry type.

==== A temporal data type for a time series;

The schema definition for the time series object shown below could be added as `#/$defs/timeSeries` in the JSON Schema of the "time" member. 

[source,json,linenumbers]
----
include::examples/extensions/timeSeries.json[]
----

The following member would then be added to `#/oneOf/1/properties`.

[source,json,linenumbers]
----
"timeSeries": { 
    "$ref": "#/$defs/timeSeries" 
}
----

==== Coordinate reference system as PROJJSON

The schema definition for the by-value CRS object shown below could be added as `#/$defs/refsys-byvalue` in the JSON Schema of the "coordRefSys" member. 

[source,json,linenumbers]
----
include::examples/extensions/refsys-byvalue.json[]
----

"PROJJSON" would also be added to `\#/$defs/refsys-custom/properties/type/not/enum` and `{ "$ref": "#/$defs/refsys-byvalue" }` would be added to `#/$defs/single-refsys/oneOf`.
