[#examples]
[appendix]
:appendix-caption: Annex
== Examples (Informative)

=== A building feature

The following feature instance is an example of a building feature that includes all new JSON-FG capabilities.

[#example_building,reftext='{listing-caption} {counter:listing-num}']
.Building with a polyhedron geometry and the polygon footprint
====
[source%unnumbered,json,linenumbers]
----
include::examples/building.json[]
----
====

=== A homogeneous feature collection

The following feature collection consists of airport features from the Zoomstack dataset of Ordnance Survey Great Britain. All features have the same feature type ("Airport") with a point geometry (geometry dimension: 0).

The feature collection has been reduced to the first two and the last feature to reduce the size of the example.

[#example_airports,reftext='{listing-caption} {counter:listing-num}']
.Airports in Great Britain
====
[source%unnumbered,json,linenumbers]
----
include::examples/airports.json[]
----
====

[#extending_jsonfg]
=== Extending JSON-FG

This section illustrates how JSON-FG can be extended with 

* new geometry types Arc and Circle;
* a new temporal data type for a time series;
* the capability to provide a coordinate reference system definition as a PROJJSON object.

If the extension would be specified in a hypothetical part 2 of JSON-FG, the extension could update the JSON schema definitions as described in the following sub-sections.

If the same extensions are specified by a community, they would copy the relevant JSON-FG schemas and extend them as described in the sub-sections. Unchanged schemas like the JSON schemas for the "geometry" and "featureType" members or for a link do not need to be copied and can reference the JSON-FG schemas.

==== Geometry types Arc and Circle

The schema definition for the new geometry objects "Arc" and "Circle" shown below could be added as `\#/$defs/Arc` and `#/$defs/Circle` in the JSON schema of geometry objects. 

[source,json,linenumbers]
----
include::examples/arc.json[]
----

[source,json,linenumbers]
----
include::examples/circle.json[]
----

"Arc" and "Circle" would also be added to `#/$defs/CustomGeometry/properties/type/not/enum`.

==== A temporal data type for a time series;

The schema definition for the time series object shown below could be added as `#/$defs/timeSeries` in the JSON schema of the "time" member. 

[source,json,linenumbers]
----
include::examples/timeSeries.json[]
----

The following member would then be added to `#/oneOf/1/properties`.

[source,json,linenumbers]
----
"timeSeries": { 
    "$ref": "#/$defs/tileSeries" 
}
----

==== Coordinate reference system as PROJJSON

The schema definition for the by-value CRS object shown below could be added as `#/$defs/refsys-byvalue` in the JSON schema of the "coordRefSys" member. 

[source,json,linenumbers]
----
include::examples/refsys-byvalue.json[]
----

"PROJJSON" would also be added to `\#/$defs/refsys-custom/properties/type/not/enum` and `{ "$ref": "#/$defs/refsys-byvalue" }` would be added to `#/$defs/single-refsys/oneOf`.
