:req-class: core
[#rc_{req-class}]
== Requirements Class "Core"

[cols="2,7",width="90%"]
|===
^|*Requirements Class* |http://www.opengis.net/spec/{standard}/{m_n}/req/{req-class} 
|Target type |JSON objects
|Dependency |<<rfc7946,RFC 7946: The GeoJSON Format>>
|Indirect Dependency |<<rfc3339,RFC 3339: Date and Time on the Internet: Timestamps>>
|Indirect Dependency |<<ogc06_103r4,Simple feature access - Part 1: Common architecture>>
|===

The Requirements Class "Core" specifies provisions for JSON-FG root objects. 

A JSON-FG root object is a JSON object 

* that is either a feature collection, feature, or geometry;
* that is not contained in another JSON-FG object;
* that meets all requirements described in this clause; and 
* that meets all requirements stated in the <<rfc7946,GeoJSON standard>> for feature collections, features, and GeoJSON geometries.

:req: schema-valid
[#{req-class}_{req}]
=== Structure of a JSON-FG root object

[width="90%",cols="2,7a"]
|===
^|*Requirement {counter:req-num}* |/req/{req-class}/{req}
^|A |The JSON object SHALL validate against the <<schema-jsonfg-root-object>>.
|===

NOTE: While every JSON-FG root object must validate against the schema, executing the validation is only necessary when testing conformance. Implementations reading or writing JSON-FG do not have to perform validation. It is also not necessary to publish application- or community-specific schemas that describe the schema of the feature properties to conform to the Core requirements class.

In requirements and recommendations, the following terms have to be interpreted as follows:

* JSON-FG root object: refers to standaridation target;
* JSON-FG object: refers to a JSON-FG object that is either the JSON-FG root object or a JSON-FG that is a child object outside of any "properties" member;
* JSON-FG feature: refers to a JSON-FG object that is a feature;
* JSON-FG geometry: refers to a JSON-FG object that is a geometry;
* JSON-FG feature collection: refers to a JSON-FG object that is a feature collection.

=== Metadata

:req: metadata
[#{req-class}_{req}]
==== Conformance declaration

[width="90%",cols="2,7a"]
|===
^|*Requirement {counter:req-num}* |/req/{req-class}/{req}
^|A |The JSON-FG root object SHALL include a "conformsTo" member.
^|B |The "conformsTo" member SHALL include at least the value `"http://www.opengis.net/spec/json-fg-1/{m_n}/conf/{req-class}"`.
^|C |Every other JSON-FG object SHALL NOT include a "conformsTo" member.
|===

NOTE: Strictly, this requirement is not necessary as it is implied by requirement `/req/{req-class}/schema-valid`. It is, however, included for clarity.

=== Temporal information

:req: instant
[#{req-class}_{req}]
==== Instants

[width="90%",cols="2,7a"]
|===
^|*Requirement {counter:req-num}* |/req/{req-class}/{req}
^|A |If the "time" value in any JSON-FG feature includes a "date" member, the value SHALL conform to <<rfc3339,RFC 3339 (Date and Time on the Internet: Timestamps)>> and match the production rule `full-date`.
^|B |If the "time" value in any JSON-FG feature includes a "timestamp" member, the value SHALL conform to <<rfc3339,RFC 3339 (Date and Time on the Internet: Timestamps)>> and match the production rule `date-time`.
|===

NOTE: Strictly, this requirement is not necessary as it is implied by requirement `/req/{req-class}/schema-valid`. It is, however, included for clarity.

:req: interval
[#{req-class}_{req}]
==== Intervals

[width="90%",cols="2,7a"]
|===
^|*Requirement {counter:req-num}* |/req/{req-class}/{req}
^|A |If the "time" value in any JSON-FG feature includes an "interval" member, each array item SHALL be a string that is a double-dot ("..") or conforms to <<rfc3339,RFC 3339 (Date and Time on the Internet: Timestamps)>> and match one of the following production rules: `full-date` (a date) or `date-time` (a timestamp).
^|B |If the start is a date, the end SHALL be a date, too, or "..".
^|C |If the start is a timestamp, the end SHALL be a timestamp, too, or "..".
^|D |If neither the start and the end are "..", the start SHALL be earlier than or equal to the end.
|===

NOTE: Strictly, A to C of this requirement are not necessary as the statements are implied by requirement `/req/{req-class}/schema-valid`. They are, however, included for clarity.

:req: instant-and-interval
[#{req-class}_{req}]
==== Instants and intervals

[width="90%",cols="2,7a"]
|===
^|*Requirement {counter:req-num}* |/req/{req-class}/{req}
^|A |If the "time" value in any JSON-FG feature includes both a "date" and a "timestamp" member, the `full-date` parts SHALL be identical.
^|B |If the "time" value in any JSON-FG feature includes both a "timestamp" and an "interval" member with start/end dates, the interval SHALL contain the date of the timestamp.
^|C |If the "time" value in any JSON-FG feature includes both a "timestamp" and an "interval" member with start/end timestamps, the interval SHALL contain the timestamp.
^|D |If the "time" value in any JSON-FG feature includes both a "date" and an "interval" member with start/end dates, the interval SHALL contain the date.
^|E |If the "time" value in any JSON-FG feature includes both a "date" and an "interval" member with start/end timestamps, the interval SHALL include timestamps on the date.
|===

:req: utc
[#{req-class}_{req}]
==== Time zones

[width="90%",cols="2,7a"]
|===
^|*Requirement {counter:req-num}* |/req/{req-class}/{req}
^|A |Timestamps in the "time" member in any JSON-FG feature SHALL use "Z" (UTC) as the time zone.
|===

NOTE: Strictly, this requirement is not necessary as it is implied by requirement `/req/{req-class}/schema-valid`. It is, however, included for clarity.

=== Geometry

:req: coordinate-dimension
[#{req-class}_{req}]
==== Coordinate dimension

[width="90%",cols="2,7a"]
|===
^|*Requirement {counter:req-num}* |/req/{req-class}/{req}
^|A |All positions in a geometry in the "geometry" members in any JSON-FG feature SHALL have the same dimension.
^|A |All positions in a geometry in the "place" members in any JSON-FG feature SHALL have the same dimension.
|===

:req: geometry-wgs84
[#{req-class}_{req}]
==== "geometry" in longitude/latitude

[width="90%",cols="2,7a"]
|===
^|*Requirement {counter:req-num}* |/req/{req-class}/{req}
^|A |The first element of each position in the "geometry" members in any JSON-FG feature SHALL be between -180 and +180.
^|B |The second element of each position in the "geometry" members in any JSON-FG feature SHALL be between -90 and +90.
|===

NOTE: The unit of the values is decimal degrees.

:req: geometry-no-jsonfg-extension
[#{req-class}_{req}]
==== "geometry" without JSON-FG extensions

[width="90%",cols="2,7a"]
|===
^|*Requirement {counter:req-num}* |/req/{req-class}/{req}
^|A |The "geometry" members in any JSON-FG feature SHALL not include any members specified by JSON-FG (from this Standard: "coordRefSys", "measures").
|===

NOTE: Strictly, this requirement is not necessary as it is implied by requirement `/req/{req-class}/schema-valid`. It is, however, included for clarity.

:req: geom-valid
[#{req-class}_{req}]
==== "place" geometries are valid

[width="90%",cols="2,7a"]
|===
^|*Requirement {counter:req-num}* |/req/{req-class}/{req}
^|A |If the "place" value in any JSON-FG feature is of geometry type "Point", "MultiPoint", "LineString", "MultiLineString", "Polygon",  "MultiPolygon" or "GeometryCollection", the geometry SHALL be valid geometries according to <<ogc06_103r4,Simple feature access - Part 1: Common architecture>>.
|===

NOTE: If the geometry type is not one the listed types, the validity of the geometry is specified in the requirements class that defines the geometry type.

:req: place
[#{req-class}_{req}]
==== No point, line string or polygon geometry in WGS 84 longitude/latitude in "place"

[width="90%",cols="2,7a"]
|===
^|*Requirement {counter:req-num}* |/req/{req-class}/{req}
^|A |If the "place" value in any JSON-FG feature is of geometry type "Point", "MultiPoint", "LineString", "MultiLineString", "Polygon", "MultiPolygon" or "GeometryCollection" and does not include a "measures" member the CRS SHALL not be `"http://www.opengis.net/def/crs/OGC/0/CRS84"` or `"http://www.opengis.net/def/crs/OGC/0/CRS84h"` (WGS 84 with axis order longitude/latitude).
|===

[[determine-crs]]
The CRS of a "place" geometry is determined as follows: 

* If the geometry has a member "coordRefSys", the CRS is identified by the value. 
** Otherwise inspect the parent object and repeat until the JSON-FG root object.
* If no "coordRefSys" member has been found, the CRS is `"http://www.opengis.net/def/crs/OGC/0/CRS84"`, if the position has two coordinates (excluding a measure coordinate), or `"http://www.opengis.net/def/crs/OGC/0/CRS84h"`, if the position has three coordinates (excluding a measure coordinate).
* Otherwise the CRS is identified by the value of "coordRefSys" member.

:req: same-crs
[#{req-class}_{req}]
==== All primary geometries are in the same CRS

[width="90%",cols="2,7a"]
|===
^|*Requirement {counter:req-num}* |/req/{req-class}/{req}
^|A |A "coordRefSys" member SHALL only be included in the JSON-FG root object and not in any other JSON-FG objects.
|===

This includes geometries that are embedded in other geometries. For example,
- the "CompoundCurve" geometry specified in the Requirements Class "Circular Arcs" includes embedded curve geometries, which cannot include a "coordRefSys" member;
- the "Prism" geometry specified in the Requirements Class "Prisms" includes an embedded 2D base geometry, which cannot include a "coordRefSys" member.

NOTE: Strictly, this requirement is not necessary as it is implied by requirement `/req/{req-class}/schema-valid`. It is, however, included for clarity.

:req: fallback
[#{req-class}_{req}]
==== Fallback geometry in "geometry"

[width="90%",cols="2,7a"]
|===
^|*Requirement {counter:req-num}* |/req/{req-class}/{req}
^|A |If both the "place" and the "geometry" member in a JSON-FG feature are not `null`, the values of both members SHALL not be identical.
|===

:req: axis-order
[#{req-class}_{req}]
==== Axis order of coordinates

[width="90%",cols="2,7a"]
|===
^|*Requirement {counter:req-num}* |/req/{req-class}/{req}
^|A |In any JSON-FG geometry, the coordinates of each position SHALL be expressed according to the https://portal.opengeospatial.org/files/?artifact_id=76024[OGC Axis Order Policy] and SHALL be in the axis order defined by the closest-to-scope CRS.
|===

:rec: place-crs
[#{req-class}_{rec}]
==== Coordinate values in "place"

[width="90%",cols="2,7a"]
|===
^|*Recommendation {counter:rec-num}* |/rec/{req-class}/{rec}
^|A |The first element of each position in the "place" members in any JSON-FG feature SHOULD be in the valid range for the first coordinate axis of the CRS.
^|B |The second element of each position in the "place" members in any JSON-FG feature SHOULD be in the valid range for the second coordinate axis of the CRS.
|===

See the <<determine-crs,description above>> how to determine the CRS of a JSON-FG geometry.

NOTE: This is only a recommendation, and not a requirement. This is because there are often valid reasons to have coordinates outside of the range, for example outside of a UTM zone that covers most of the area of a dataset.
