== Scope

The OGC Features and Geometries JSON (JSON-FG) Standard extends the <<rfc7946,GeoJSON format>> to support a limited set of additional capabilities that are out-of-scope for GeoJSON, but that are important for a variety of use cases involving feature data.

The JSON-FG Standard specifies the following minimal extensions to the GeoJSON format:

* The ability to use Coordinate Reference Systems (CRSs) other than WGS 84 (OGC:CRS84);
* The ability to use non-Euclidean metrics, in particular ellipsoidal metrics;
* Support for solids and prisms as geometry types;
* The ability to encode temporal characteristics of a feature; and
* The ability to declare the type and the schema of a feature.

Geographic features, their properties, and their spatial extents that can be represented as GeoJSON objects are encoded as GeoJSON. Additional information not specified in the GeoJSON RFC is mainly encoded in additional members of the GeoJSON objects. The additional members use keys that do not conflict with existing GeoJSON keys. This was done so that existing and future GeoJSON clients can continue to successfully parse and understand GeoJSON encoded content. JSON-FG enabled clients will also be able to parse and understand the additional members.

<<json-schema,JSON Schema>> is used to formally specify the JSON-FG syntax.
