== Terms, Definitions and Abbreviated Terms

=== Terms and Definitions

This document uses the terms defined in https://portal.ogc.org/public_ogc/directives/directives.php[OGC Policy Directive 49], which is based on the ISO/IEC Directives, Part 2, Rules for the structure and drafting of International Standards. In particular, the word “shall” (not “must”) is the verb form used to indicate a requirement to be strictly followed to conform to this Standard and OGC documents do not use the equivalent phrases in the ISO/IEC Directives, Part 2.

This document also uses terms defined in the OGC Standard for Modular specifications (https://portal.opengeospatial.org/files/?artifact_id=34762[OGC 08-131r3]), also known as the 'ModSpec'. The definitions of terms such as standard, specification, requirement, and conformance test are provided in the ModSpec.

For the purposes of this document, the following additional terms and definitions apply.

coordinate::
one of a sequence of numbers designating the **position** of a point [<<ogc18_005r4,OGC Topic 2>>]

coordinate reference system::
coordinate system that is related to an object by a datum [<<ogc18_005r4,OGC Topic 2>>]

NOTE: More information about coordinate reference systems and common problems when dealing with coordinates may be found in the <<sdwbp,W3C/OGC Spatial Data on the Web Best Practice>> in the section link:https://www.w3.org/TR/2017/NOTE-sdw-bp-20170928/#CRS-background['Coordinate Reference Systems (CRS)'].

feature::
abstraction of real world phenomena [ISO 19101-1:2014]

NOTE: More details about the term 'feature' may be found in the <<sdwbp,W3C/OGC Spatial Data on the Web Best Practice>> in the section link:https://www.w3.org/TR/2017/NOTE-sdw-bp-20170928/#spatial-things-features-and-geometry['Spatial Things, Features and Geometry'].

feature collection::
a set of *features* from a dataset

feature schema::
schema that describes the properties of a *feature type*

feature type::
class of *features* having common characteristics [ISO 19156:2023]

JSON document::
an information resource (series of octets) described by the "application/json" media type [<<json-schema,JSON Schema 2020-12>>]

NOTE: The terms "JSON document", "JSON text", and "JSON value" are interchangeable.

JSON object::
an unordered set of name/value pairs mapping the name to a JSON value [<<json-schema,JSON Schema 2020-12>>, modified]

JSON-FG document::
a **JSON document** that contains a JSON-FG root object

JSON-FG feature::
a **JSON object** that validates against the JSON-FG feature schema

JSON-FG feature collection::
a **JSON object** that validates against the JSON-FG feature collection schema

JSON-FG geometry::
a **JSON object** that validates against the JSON-FG geometry schema

JSON-FG object::
a **JSON object** that is either a JSON-FG feature, a JSON-FG feature collection, or a JSON-FG geometry

JSON-FG root object::
a **JSON-FG object** that is not a direct children of another JSON-FG object

<JSON> key::
the name of a *member*

<JSON> member::
a name/value pair in a **JSON object**

position::
a sequence of numbers representing a point in a **coordinate reference system**

primary geometry::
the geometry that the publisher considers as the most important spatial characteristic of a *feature* (<<OAFeat-5,OGC API - Features - Part 5: Schemas>>)

NOTE: A feature can be described by multiple spatial properties. For example, a radio tower can have a property with a point value that describes the location of the tower and another property with a multi-polygon value that describes the area of coverage. Some feature formats can represent only a single geometry per feature. In those cases, the primary geometry will be used when the feature is encoded in such a format.

NOTE: The primary geometry of a feature can also vary depending on the zoom level. At a smaller scale, the primary geometry could be a point while a polygon could be used at a larger scale.

primary temporal information::
the time instant or time interval that the publisher considers as the most important temporal characteristic of a *feature* (<<OAFeat-5,OGC API - Features - Part 5: Schemas>>)

NOTE: A feature can be described by multiple temporal properties. For example, an event can have a property with an instant or interval when the event occurred or will occur and another property when the event was recorded in the dataset. The primary temporal information can also be built from two properties, e.g., when the feature has two properties describing the start instant and end instant of an interval.

profile::
additional semantics (constraints, conventions, extensions) that are associated with a resource representation, in addition to those defined by the media type (<<rfc6906,RFC 6906: The 'profile' Link Relation Type>>)

publisher::
entity responsible for making a resource available (https://www.dublincore.org/specifications/dublin-core/dcmi-terms/#http://purl.org/dc/terms/publisher[Dublin Core Metadata Initiative - DCMI Metadata Terms])

=== Abbreviated Terms

API:: Application Programming Interface

CRS:: Coordinate Reference System

JSON:: JavaScript Object Notation

JSON-FG:: OGC Features and Geometries JSON

JSON-LD:: JSON for Linking Data

OGC:: Open Geospatial Consortium

SWG:: Standards Working Group

WGS 84:: World Geodetic System 1984 