:req-class: prisms
[#rc_{req-class}]
== Requirements Class "Prisms"

[cols="2,7",width="90%"]
|===
^|*Requirements Class* |http://www.opengis.net/spec/{standard}/{m_n}/req/{req-class} 
|Target type |JSON-FG root objects
|Dependency |<<rc_core>>
|===

The "Prisms" Requirements Class adds provisions for extruded geometries in a 3D CRS that may be of type <<Prism>> or <<MultiPrism>>.

=== Metadata

:req: metadata
[#{req-class}_{req}]
==== Conformance declaration

[width="90%",cols="2,7a"]
|===
^|*Requirement {counter:req-num}* |/req/{req-class}/{req}
^|A |The "conformsTo" member of the JSON-FG root object SHALL include the value `"http://www.opengis.net/spec/json-fg-1/{m_n}/conf/{req-class}"`.
|===

=== Geometry

:req: coordinates
[#{req-class}_{req}]
==== Coordinates

[width="90%",cols="2,7a"]
|===
^|*Requirement {counter:req-num}* |/req/{req-class}/{req}
^|A |All positions in the "base" member of a JSON-FG geometry of type "Prism" SHALL have a coordinate dimension of two (2) - or three (3), if measure values are included (see <<rc_measures>>).
^|B |The "lower" and "upper" values of each Prism SHALL be in the valid range for the third coordinate axis of the CRS.
^|C |In a Prism, the "lower" value SHALL be equal or smaller than the "upper" value.
^|D |The CRS of each Prism geometry SHALL have three dimensions (a 3D CRS or an ad-hoc compound CRS consisting of a horizontal 2D CRS and a vertical CRS).
|===

NOTE: There is no need to state a requirement that base geometries have to be valid, as this is already stated in the <<rc_core>> requirements class for Simple Feature geometries or in the requirements class that defines the base geometry for other geometry types.
