== Introduction

=== Motivation

JavaScript Object Notation (JSON) is a popular encoding format for geospatial data. The light weight, simple syntax, and clear human and machine readability of JSON as well as universal support in all modern programming languages appeals to developers. GeoJSON has become a very popular encoding and is supported in most deployments of APIs implementing OGC API Features. However, GeoJSON has limitations that prevent or limit its use in some cases, including:

* WGS 84 is the only coordinate reference system that is supported;
* Geometries are restricted to points, curves and surfaces with linear interpolation; and
* No general capability is available to specify the schema of a feature, its type or its temporal characteristics.

=== Scenarios

The following general scenarios are useful in understanding the principles that have been used in the JSON-FG design:

1. In order to display features in a 3D scene, a client accesses a Web API that shares a building dataset and that implements OGC API Features. The scene uses a projected CRS, e.g. `\http://www.opengis.net/def/crs/EPSG/0/5555`. The API advertises support for both GeoJSON and JSON-FG as feature representations and support for the projected CRS in addition to WGS 84.
2. A client accesses a JSON-FG file with building data that is stored locally or as a static file in the cloud (e.g., in an Object Storage or a GitHub repository). Again, the file is accessed to display features in a 3D scene and a time slider is used to suppress features outside of a user-specified time interval.

The following description uses `application/vnd.ogc.fg+json` as the media type for JSON-FG.

==== Using a GeoJSON client

The client supports only GeoJSON and not JSON-FG.

In the first scenario (API access), the client requests the GeoJSON representation of the feature using `Accept: application/geo+json`. This is because the client only supports a GeoJSON feature encoding. The response will in general not include the JSON-FG extensions and is provided in WGS 84 with axis order longitude/latitude as the spatial CRS. The client will transform the geometry to the projected CRS.

In the second scenario (file access), the client has no access to a media type and has to inspect the file to determine if the file is a GeoJSON document that it can process. While the document is a JSON-FG document it is also a valid GeoJSON document, so the client is still able to use and display the features. The client will, however, not understand the additional information introduced by JSON-FG. Any JSON-FG extensions must not conflict with existing GeoJSON members to avoid issues for GeoJSON clients parsing JSON-FG documents.

==== Using a JSON-FG client

The client supports GeoJSON and JSON-FG.

In the first scenario (API access), the client will typically request the JSON-FG representation of the feature using an HTTP header like `Accept: application/vnd.ogc.fg+json, application/geo+json;q=0.8` and a `crs=http://www.opengis.net/def/crs/EPSG/0/5555` query parameter. The header states that the client prefers JSON-FG, but will also accept GeoJSON, if JSON-FG is not available. The response will include the headers `Content-Type: application/vnd.ogc.fg+json` as well as `Content-Crs: \http://www.opengis.net/def/crs/EPSG/0/5555` and include the JSON-FG building blocks including the geometry in the requested projected CRS and temporal information.

In the second scenario (file access), the client is in the same position as the GeoJSON client - it has no access to a media type and has to inspect the file to determine - if the file is a GeoJSON, JSON-FG or some other kind of document that it does not understand. JSON-FG documents include explicit declarations that conform to both GeoJSON and JSON-FG. Therefore, the client can identify the document as a JSON-FG document and process the content. Since the JSON-FG document provides spatial and temporal information about each feature, the client can zoom in on the features and, for example, provide a time slider so that the user can filter the features that are displayed.
