== Introduction

=== Motivation

JavaScript Object Notation (JSON) is a popular encoding format for geospatial data. The light weight, simple syntax, and clear human and machine readability of JSON as well as universal support in all modern programming languages appeals to developers. The GeoJSON format as defined in <<rfc7946,IETF RFC 7946>> is a very popular JSON encoding for geographic data.  GeoJSON is supported by many commercial and open-source geospatial technology products and libraries.  GeoJSON is also supported in most deployments of APIs implementing the OGC API Features Standard. However, GeoJSON has limitations that prevent or limit its use in certain cases, including:

* WGS 84 is the only allowed Coordinate Reference System (CRS);
* Geometries are restricted to points, curves, and surfaces with linear interpolation; and
* No general capability is available to specify the schema of a feature, its type, or its temporal characteristics.

=== Scenarios

The following general scenarios are useful in understanding the principles that were used in the JSON-FG design:

1. In order to display features in a 3D scene, a client accesses a Web API that shares a building dataset and that implements the OGC API Features Standard. The scene uses a projected CRS, such as `EPSG:5555`. The API advertises support for GeoJSON for representing features including JSON-FG extensions as well as support for the projected CRS in addition to WGS 84.
2. A client accesses a JSON-FG document with building data that is stored locally or as a static file in the cloud (e.g., in an Object Storage or a GitHub repository). Again, the file is accessed to display features in a 3D scene and a time slider is used to suppress features outside of a user-specified time interval.

==== Using a GeoJSON client

Consider the case where the client implementation only supports GeoJSON and not JSON-FG.  An assumption is that the client does support CRS transformations.

In the first scenario (API access), the client requests the GeoJSON representation of the feature using `Accept: application/geo+json`. This is because the client only knows the GeoJSON feature encoding as specified in RFC 7946. The response should not include the JSON-FG extensions. Further, the response is provided in the WGS 84 CRS with axis order longitude/latitude. The client can then transform the geometry to the projected CRS.

In the second scenario (file access), the client has no access to a media type and has to inspect the file to determine, if the file is a GeoJSON document that it can process. While the JSON document consists of a JSON-FG object, it is also a valid GeoJSON object.  Therefore, the client is still able to use and display the features. The client will, however, not understand the additional information introduced by JSON-FG. To avoid issues for GeoJSON clients parsing JSON-FG objects, the names of any JSON-FG extension members must not conflict with the names of existing GeoJSON members to avoid issues for GeoJSON clients parsing JSON-FG objects.

==== Using a JSON-FG client

The client implementation supports GeoJSON including the JSON-FG extensions.

In the first scenario (API access), the client will typically request the JSON-FG representation of the feature using an `Accept: application/geo+json` header and a `profile` query parameter selecting a JSON-FG profile (e.g., `profile=jsonfg`) and a `crs=http://www.opengis.net/def/crs/EPSG/0/5555` query parameter to request the coordinates in the projected CRS. The response will include the headers `Content-Type: application/geo+json`, `Content-Crs: \http://www.opengis.net/def/crs/EPSG/0/5555` as well as `Link: <\http://www.opengis.net/def/profile/OGC/0/jsonfg>; rel="profile"` and include the JSON-FG building blocks including the geometry in the requested projected CRS and temporal information.

In the second scenario (file access), the JSON-FG client is in the same position as the GeoJSON client.  The client has no access to media type and profile information. The client has to inspect the file to determine the type. The file could be GeoJSON, JSON-FG or some other kind of document that the client does not understand. JSON-FG documents include a "conformsTo" member that declares that the JSON document conforms to one or more JSON-FG 1.0 conformance classes. Therefore, the client can identify the document as a JSON-FG document and process the content. Since the JSON-FG document provides spatial and temporal information about each feature, the client can zoom in on the features and, for example, provide a time slider so that the user can filter the features that are displayed.
