[[building_blocks]]
== JSON-FG building blocks

This chapter describes the JSON building blocks to extend GeoJSON features and feature collections. The following chapters specify the formal requirements classes.

The Annex '<<considerations>>' contains considerations for each of the JSON-FG building blocks.

Known open issues are included in notes with #highlighted# text.

NOTE: #Including information in some kind of 'header' would be helpful. This would support how a client should parse the content (as JSON-FG with its extensions, as standard GeoJSON, etc.), in particular, if the data is parsed as a file, not as an API response with a content type header.#

=== Overview

The following JSON building blocks are specified by this Standard:

* <<time>>
* <<place>>
* <<ref-sys>>
* <<feature-types>>
* <<schema-ref>>

An additional topic that was discussed are relationships between a feature and other web resources that are represented as links. This standard does not mandate a specific approach for representing relationships as links. However, Annex '<<relationships_and_links>>' documents and discusses patterns of how to represent relationships as links.

Annex '<<examples>>' has examples of JSON-FG documents.

[[time]]
=== Temporal information

==== Overview

Many features have a geometry that provides information about the primary spatial characteristics of the feature. In GeoJSON, this information is encoded in the "geometry" member. Features often also include temporal information. In most cases this is either an instant (e.g., an event) or an interval (e.g., an activity or a temporal validity). In OGC API Features this is reflected in the http://www.opengis.net/doc/IS/ogcapi-features-1/1.0#_parameter_datetime[parameter "datetime"] for temporal filtering of features that is supported by all compliant APIs.

JSON-FG adds support for the most common case: Associating a feature with a single temporal instant or interval in the Gregorian calendar.

More complex cases and other temporal coordinate reference systems are out-of-scope for this Standard and might be specified in future extensions.

==== Description

Features can have temporal properties. These will typically be included in the "properties" member.

* In many datasets all temporal properties are instants (represented by a date or a timestamp) and intervals will be described using two temporal instants, one for the start and one for the end.
* Multiple temporal properties are sometimes used to describe different temporal characteristics of a feature. For example, the time instant or interval when the information in the feature is valid (sometimes called "valid time") and the time when the feature was recorded in the dataset (sometimes called "transaction time"). Another example is the https://www.ogc.org/standards/om[Observations & Measurements standard], where an observation has multiple temporal properties including "phenomenon time", "result time" and "valid time".

Like GeoJSON, JSON-FG does not place constraints on the information in the "properties" member. JSON-FG specifies a new JSON member in a feature object (key: "time"). The member describes temporal information (an instant or an interval) that can be used by clients without a need to inspect the "properties" member or to understand the schema of the feature. Clients that are familiar with a dataset can, of course, inspect the information in the "properties" member instead of inspecting the "time" member.

The publisher of the data needs to decide which temporal feature properties are used in the "time" member.

The value of "whtimeen" is either `null` (no temporal information) or an object.

.Properties of the "time" object
[cols="20,10a,70a",options="header"]
!===
|Property |Type |Description
|date |string |An instant with a granularity of a date. See below for more details about instants.
|timestamp |string |An instant with the granularity of a timestamp. See below for more details about instants.
|interval |[ string ] |An interval, described by an array of the two instants (start and end). See below for more details about intervals.
!===

It is valid to include both an instant and an interval, if both values intersect. Clients should use the interval and may use the instant to determine the temporal characteristics of the feature.

The "time" object may be extended with additional members. Clients processing a "time" object must be prepared to parse additional members. Clients should ignore members that they do not understand. For example, in cases where the "time" member neither includes an "instant" or "interval", a client may process the feature as a feature without temporal information.

NOTE: The data publisher decides how temporal properties inside the "properties" member are encoded. The schema for the "time" member does not imply a recommendation that temporal feature properties reuse the same schema. For example, it is expected that a date-valued feature attribute will in most cases be represented as string with an RFC 3339 date value.

==== Instants

An instant is a value that conforms to https://datatracker.ietf.org/doc/html/rfc3339[RFC 3339 (Date and Time on the Internet: Timestamps)] and is consistent with one of the following production rules of the ISO 8601 profile specified in the RFC:

* `full-date` (e.g., `"1969-07-20"`)
* `date-time` (e.g., `"1969-07-20T20:17:40Z"`)

Conceptually, an instant is a "temporal entity with zero extent or duration" [<<owl-time,Time Ontology in OWL>>]. In practice, the temporal position of an instant is described using data types where each value has some duration or granularity. The value should be described with a granularity that is sufficient for the intended use of the data.

In the case of a timestamp the granularity is a second or smaller. All timestamps have to be in the time zone UTC ("Z").

In the case of a date the granularity is a day and dates as instants will be used when a granularity of a day independent of its timezone is sufficient for the intended use of the data. If that is not the case and, for example, the timezone is important for the intended use, the temporal information should be provided as an interval with start and end timestamps.

NOTE: This Standard only provides guidance how to represent feature data in JSON. It is out-of-scope for this Standard to provide guidance how to cast JSON-FG data to other data types. The Common Query Language (CQL2) standard uses the same model of instants and intervals as JSON-FG and includes additional guidance how to compare values, see the section https://docs.ogc.org/DRAFTS/21-065.html#basic-cql2_data-types-and-literals[Data types and literal values].

[#ex-time-1,reftext='{listing-caption} {counter:listing-num}']
.A date
====
[source,json,linenumbers]
----
"time" : { "date": "1969-07-20" }
----
====

[#ex-time-2,reftext='{listing-caption} {counter:listing-num}']
.A timestamp
====
[source,json,linenumbers]
----
"time" : { "timestamp": "1969-07-20T20:17:40Z" }
----
====

This describes the initial range of instant values. This range may be extended in the future to support additional use cases. Clients processing instant values must be prepared to receive other values. Clients may ignore values that they do not understand.

==== Intervals

An interval is described by start and end instants. Both start and end instants are included in the interval, i.e., the interval is closed.

Unbounded intervals ends are represented by a double-dot string ("..") for the start/end. This follows the convention of ISO 8601-2 for an open start or end.

[#ex-time-3,reftext='{listing-caption} {counter:listing-num}']
.An interval with dates
====
[source,json,linenumbers]
----
"time" : { "interval": [ "1969-07-16", "1969-07-24" ] }
----
====

[#ex-time-4,reftext='{listing-caption} {counter:listing-num}']
.An interval with timestamps
====
[source,json,linenumbers]
----
"time" : { "interval": [ "1969-07-16T05:32:00Z", "1969-07-24T16:50:35Z" ] }
----
====

[#ex-time-5,reftext='{listing-caption} {counter:listing-num}']
.An half-bounded interval
====
[source,json,linenumbers]
----
"time" : { "interval": [ "2014-04-24T10:50:18Z", ".." ] }
----
====

This describes the initial range of interval values. This range may be extended in the future to support additional use cases. Clients processing interval values must be prepared to receive other values. Clients may ignore values that they do not understand.

[[place]]
=== Geometry

==== Overview

Features typically have a geometry that provides information about the primary spatial characteristics of the feature.

In GeoJSON, this information is encoded in the "geometry" member. Geometries are according to the Simple Features Standard (2D or 2.5D points, line strings, polygons or aggregations of them) in WGS 84 as the coordinate reference system (OGC:CRS84 or OGC:CRS84h).

A key motivation for JSON-FG is to support additional requirements, especially other coordinate reference systems and solids.

To avoid confusing existing GeoJSON readers, such geometries will be provided in a new member in the feature object with the key "place".

==== Description

The primary geometry of a feature is provided in the "geometry" and/or "place" members of the feature object. The value of both keys is an object representing a geometry - or `null`.

The value of the "geometry" member is specified in the GeoJSON standard.

The value range of the "place" member is an extended and extensible version of the value range of the "geometry" member:

* Extended by additional geometry objects (additional JSON-FG geometry types <<Polyhedron>>, <<MultiPolyhedron>>, <<Prism>> and <<MultiPrism>>) as well as by the capabilities to <<ref-sys,declare the coordinate reference system of the coordinates>>.
* Future parts of Features and Geometries JSON or community extensions may specify additional members or additional geometry types. JSON-FG readers should be prepared to parse values of "place" that go beyond the schema that is implemented by the reader. Unknown members should be ignored and geometries that include an unknown geometry type should be mapped to `null`.

===== Use of "geometry" and/or "place"

If the geometry can be represented as a valid GeoJSON geometry (one of the GeoJSON geometry types, in WGS84), it is encoded as the value of the "geometry" member. The "place" member has the value `null`.

If the geometry cannot be represented as a valid GeoJSON geometry, it is encoded as the value of the "place" member. 

In addition, a valid GeoJSON geometry may be provided in the "geometry" member in the coordinate reference system WGS84 as specified in the GeoJSON standard (otherwise "geometry" is set to `null`). The geometry in "geometry" is a fallback for readers that support GeoJSON, but not JSON-FG. This could be a simplified geometry, like the building footprint in the <<example_building,example "building with a polyhedron geometry and the polygon footprint">> instead of the solid geometry or the same point/line string/polygon geometry, but in WGS 84 (potentially with fewer vertices to reduce the file size). It is the decision of the data provider or a community of interest, how the fallback geometry in the coordinate reference system WGS84 is derived from the geometry in the "place" member. In the example, it is the footprint of the building, but it also could be a representative point (to reduce the data volume) or a 3D MultiPolygon representing the outer shell of the polyhedron (for clients that support visualizations in 3D).

The presence of such fallback geometries in a JSON-FG document is indicated by a value "geojson" in the media type parameter "compatibility" (see <<application_fg_json>>).

===== Metrics

If the CRS uses longitude and latitude as coordinate axes, clients should perform geometrical computations - including computation of length or area on the curved surface that approximates the earth's surface. Details are provided in the drafts of <<ogc20_070,Features and Geometry - Part 2: Metrics>>.

Note that this differs from GeoJSON which states:

[quote, GeoJSON (RFC 7946)]
A line between two positions is a straight Cartesian line, the shortest line between those two points in the coordinate reference system.
In other words, every point on a line that does not cross the antimeridian between a point (lon0, lat0) and (lon1, lat1) can be calculated as `F(lon, lat) = (lon0 + (lon1 - lon0) * t, lat0 + (lat1 - lat0) * t)` with t being a real number greater than or equal to 0 and smaller than or equal to 1. Note that this line may markedly differ from the geodesic path along the curved surface of the reference ellipsoid.

===== Polyhedron

A solid is defined by its bounding surfaces. Each bounding surface is a closed, simple surface, also called a shell. 

Each solid has a unique exterior shell and any number of shells that are inside the exterior shell and that describe voids. The interior shells do not intersect each other and cannot contain another interior shell.

A _polyhedron_ is a solid where each shell is a multi-polygon. 'Closed' means that the multi-polygon shell is watertight, it splits space into two distinct regions: inside and outside of the shell. 'Simple' means that the polygons that make up the shell do not intersect, they only touch each other along their common boundaries.

<Add figure(s) illustrating polyhedra.>

The JSON representation of the coordinates of a polyhedron is a non-empty array of _multi-polygon_ arrays. Each _multi-polygon_ array is a shell. The first shell is the exterior boundary, all other shells are voids.

The dimension of all positions is three.

===== MultiPolyhedron

A _multi-polyhedron_ is a collection of _polyhedron_ objects. These are arbitrary aggregations; i.e., there is no assumption regarding the topological relationships between the _polyhedron_ objects, but in most cases the _polyhedron_ objects will not intersect each other. 

NOTE: According to ISO 19107:2020 ("Spatial schema"), the geometry of the _multi-polyhedron_ is the set theoretic union of all _polyhedron_ objects. For example, if there are overlapping _polyhedron_ objects, the volume of the _multi-polyhedron_ will be smaller than the sum of the _polyhedron_ volumes.

The collection is represented as a JSON array. The order of the polyhedron geometry objects in the array is not significant.

===== Prism

A _prism_ is defined by a base shape (e.g. Polygon or Circle) that is then extruded from some optional lower limit to an upper limit.

The limits are measured relative to a specified 3D CRS.  That is either the default 3D CRS (OGC:CRS84h) or a 3D CRS specified using <<ref-sys,coordRefSys>> key.

If the base shape is a point type then the extrusion is a line extending from the lower limit to the upper limit.

<Add figure(s) illustrating point extrusion.>

If the base shape is a line string type then the extrusion is a ribbon following the path of the line string and extending from the lower limit to the upper limit.

<Add figure(s) illustrating a ribon.>

If the base shape is a polygon type then the extrusion is a solid whose footprint takes the shape of the specified polygon and extended from the lower limit to the upper limit.  If the polygon base shape contains holes, these manifest as voids in the extruded shape.

<Add figure(s) illustrating a polygon extrusion (Toronto City Hall would be nice if I can find the data).>

===== MultiPrism

A _multi-prism_ is an array of _prism_ objects.  The order of the prism geometry objects is the array is not significant.

[[ref-sys]]
=== Reference systems

==== Overview

Without any other information, the following coordinate reference system (CRS) defaults apply in a JSON-FG document:

* Spatial CRS: WGS 84 with axis order longitude, latitude and optional ellipsoidal height, either `link:http://www.opengis.net/def/crs/OGC/1.3/CRS84[OGC:CRS84]` (2D) or `link:http://www.opengis.net/def/crs/OGC/0/CRS84h[OGC:CRS84h]` (3D);
* Temporal CRS: DateTime in Gregorian calendar, `OGC:datetime` (to be registered with the OGC Naming Authority, see <<crs-datetime-gregorian>>).

A new key "coordRefSys" is defined and can be used to assert the CRS of a JSON-FG geometry object at the collection, feature or value levels.

It is anticipated that if a CRS is asserted for a JSON-FG document, that assertion will typically be made at the top level of the document, either at the collection level or the feature level depending on the contents of the document.

==== Description

Spatio-temporal objects are specified relative to some reference system.

GeoJSON (both the current https://tools.ietf.org/html/rfc7946[RFC] and the https://geojson.org/geojson-spec.html[legacy version]) fixed the reference system for geometric values to the "WGS84 datum, and with longitude and latitude units of decimal degrees".  The https://geojson.org/geojson-spec.html[legacy version] included a "prior arrangement" provision to allow other reference systems to be used and also defined the "crs" key for specifying the reference system.  This _prior arrangement_ mechanism survived into the https://tools.ietf.org/html/rfc7946[RFC] but the accompanying "crs" key did not. The result is that there is no interoperable way to unambiguously specify a different CRS in GeoJSON and the only safe approach is to stick with OGC:CRS84(h) for GeoJSON and ignore the _prior arrangement_ provision and the old "crs" key.

Additional JSON-FG building blocks like the "place" member are not bound by these restrictions and so this Standard provides for handling reference systems in JSON-FG documents that does not interfere with anything, past or present, defined in any of the GeoJSON specifications. The GeoJSON building blocks can continue to operate as always but JSON-FG building blocks can avail themselves of enhanced CRS support.

NOTE: #Check original proposal for another alternative how to disambiguate between different JSON objects that represent a CRS by-reference, by-value, etc.#

===== Reference system values

A reference system can be specified in a JSON-FG document using a "coordRefSys" member in one of three ways:

* As a CRS reference using the URI or OGC CURIE of a simple CRS;
* As a CRS reference using the URI or OGC CURIE of a simple CRS accompanied by an optional epoch value (for dynamic CRSs);
* As an array of simple CRS references denoting an ad hoc compound reference system.

[#rs-by-simple-ref,reftext='{listing-caption} {counter:listing-num}']
.A simple reference system value by reference (URI).
====
[source,json,linenumbers]
----
"http://www.opengis.net/def/crs/EPSG/0/3857"
----
====

[#rs-by-simple-ref-curie,reftext='{listing-caption} {counter:listing-num}']
.A simple reference system value by reference (CURIE).
====
[source,json,linenumbers]
----
"[EPSG:3857]"
----
====

[#rs-by-ref-with-epoch,reftext='{listing-caption} {counter:listing-num}']
.A reference system value by reference (URI) and with an epoch.
====
[source,json,linenumbers]
----
{
  "type": "Reference",  
  "href": "http://www.opengis.net/def/crs/EPSG/0/4979",
  "epoch": 2016.47
}
----
====

[#compound-rs-by-value,reftext='{listing-caption} {counter:listing-num}']
.A ad hoc compound reference system value (using URIs)
====
[source,json,linenumbers]
----
[
  {
    "type": "Reference",  
    "href": "http://www.opengis.net/def/crs/EPSG/0/4258",
    "epoch": 2016.47
  },
  "http://www.opengis.net/def/crs/EPSG/0/7837"
]
----
====

[#compound-rs-by-value-curie,reftext='{listing-caption} {counter:listing-num}']
.A ad hoc compound reference system value (using CURIEs)
====
[source,json,linenumbers]
----
[
  {
    "type": "Reference",  
    "href": "[EPSG:4258]",
    "epoch": 2016.47
  },
  "[EPSG:7837]"
]
----
====

===== Scoping rules

Used at the feature collection level, the "coordRefSys" key asserts the coordinate reference system for JSON-FG geometry objects found anywhere in the document that are not otherwise tagged with closer-to-scope coordinate reference system information.

Used at the feature level, the "coordRefSys" key asserts the coordinate reference system for JSON-FG geometry objects found anywhere in the feature that are not otherwise tagged with closer-to-scope coordinate reference system information.

Used at the geometry level, the "coordRefSys" key asserts the coordinate reference system for the JSON-FG geometry object within which the key is contained.

Where all objects on the same level are in the same coordinate reference system, it is recommended to declare the coordinate reference system on the parent level instead of declaring it in all parallel objects.

===== Coordinate order

The order in which coordinates for JSON-FG geometry objects are expressed is defined in the https://portal.opengeospatial.org/files/?artifact_id=76024[OGC Axis Order Policy] and shall be in the axis order defined by the closest-to-scope CRS metadata.

===== Additional coordinate reference systems

For unknown coordinate reference systems, e.g. with engineering data like CAD drawings, the following CRS identifiers can be used:

* `OGC:engineering-2d` for 2D coordinates (x, y), to be registered, see <<crs-engineering-2d>>;
* `OGC:engineering-3d` for 3D coordinates (x, y, z), to be registered, see <<crs-engineering-3d>>.

[[feature-types]]
=== Feature type(s)

==== Overview

Features are often categorized by type. Typically, all features of the same type have the same schema and the same properties.

Many GIS clients depend on knowledge about the feature type when processing feature data. For example, associating a style to a feature in order to render that feature on a map.

GeoJSON is schema-less in the sense that it has no concept of feature types or feature schemas.

In most cases, a feature is an instance of a single feature type. The current draft revision of the Simple Features standard supports features that are instances of multiple types. JSON-FG, therefore, also supports multiple feature types.

The related element <<schema-ref>> specifies which elements of the JSON Schema documents are identified that the JSON-FG document conforms to. This element specifies how to represent feature type information in the JSON object that represents the feature.

==== Description

===== The "featureType" member

The feature types of a feature are declared in a member of the feature object with the key "featureType". The value is either a string (in the standard case of a single feature type) or an array of strings (to support features that instantiate multiple feature types). Each string should be a code, convenient for the use in filter expressions.

NOTE: #Should there be a capability to distinguish between feature types that "just" identify a concept, but have no associated or no well-defined schema, and feature types that have an associated schema (the schema would be linked using a "describedby" link relation type)?#

[[homogeneous-collections]]
===== Homogeneous feature collections

Some clients will process feature collections differently depending on whether the collection is homogenous with respect to the feature type or the geometry type. These clients will benefit from information that declares the feature and/or geometry type for all features in a collection.

If the JSON document is a feature collection and all features in the feature collection have the same "featureType" value, the "featureType" member can and should be added once for the feature collection. The "featureType" member can then be omitted in the feature objects. Declaring the feature type(s) once signals to clients that the feature collection is homogeneous with respect to the type, which clients can use to optimize their processing.

If the JSON document is a feature collection and all features in the feature collection have the same geometry type as their primary geometry (point, curve, surface, solid, including homogenous aggregates), a "geometryDimension" member can and should be added once for the feature collection with the dimension of the geometry (0 for points, 1 for curves, 2 for surfaces, 3 for solids, null/not set for mixed dimensions or unknown). Declaring the geometry dimension once signals to clients that the feature collection is homogeneous with respect to the dimension, which clients can use to optimize their processing.

===== Links to a semantic type

If a persistent resource exists, such as in a registry, that describes a feature type, a link to that resource with link relation type "type" should be added. In the case of multiple feature types per feature, multiple links are added.

OGC API Features already specifies a general "links" member with an array of link objects based on https://tools.ietf.org/html/rfc8288[RFC 8288 (Web linking)] and feature responses from APIs implementing OGC API Features will already include a "links" member. JSON-FG builds on this approach and includes a "type" link to a resource identifying the abstract semantic type of which the feature is considered to be an instance.

.Link properties
[cols="20,10,70",options="header"]
!===
|Property |Type |Description
|href |URI or CURIE |**REQUIRED**. The URI or OGC CURIE of a persistent resource that describes a feature type that is instantiated by the feature that is the link context.
|rel |String |**REQUIRED**. The link relation type, always "type".
|type |String |To indicate a hint about a specific media type in which the target of the link is available, set the value to that media type; for example, "text/html".
|title |String |Include this link attribute for a human readable label of the link, e.g. for use in a derived HTML representation.
!===

Additional link attributes may be added to the Link object.

[[schema-ref]]
=== Schema(s)

==== Overview

A schema is metadata about a JSON document that clients can use to validate the JSON document or to derive additional information about the content of the JSON document, such as a textual description of the feature properties or their value range.

NOTE: As of 2021, the OGC Features API Standards Working Group is working on a [specification in the OGC API Features series](https://github.com/opengeospatial/ogcapi-features/tree/master/proposals/schemas) for using JSON schemas to describe the schema of features.

This Standard provides guidance on how to include information about the schema of a JSON document that is a JSON-FG feature or feature collection.

==== Description

The <<json-schema,JSON Schema specification>> recommends to use https://json-schema.org/draft/2020-12/json-schema-core.html#rfc.section.9.5[a "describedby" link relation to the schema]:

> It is RECOMMENDED that instances described by a schema provide a link to a downloadable JSON Schema using the link relation "describedby" [...].

OGC API Features already specifies a general "links" member with an array of link objects based on https://tools.ietf.org/html/rfc8288[RFC 8288 (Web linking)]. Therefore, feature responses from APIs implementing OGC API Features will already include a "links" member. JSON-FG builds on this approach and includes a "describedby" link to a JSON Schema document, if schema information is important for the target users of the JSON feature documents.

.Link properties
[cols="20,10,70",options="header"]
!===
|Property |Type |Description
|href |URI |**REQUIRED**. The URI of a JSON Schema document that describes the JSON document that is the link context.
|rel |String |**REQUIRED**. The link relation type, which is always "describedby" for the link to the JSON Schema document.
|type |String |**REQUIRED**. To indicate that the target of the link is a JSON Schema document, set the value to "application/schema+json".
|title |String |Include this link attribute for a human readable label of the link, e.g. for use in a derived HTML representation.
!===

An example of a link object:

[source,json]
----
{
  "href": "https://demo.ldproxy.net/zoomstack/collections/airports/schema",
  "rel": "describedby",
  "type": "application/schema+json",
  "title": "JSON Schema of this document"
}
----

Additional link attributes may be added to the Link object.

Each JSON-FG document is either a feature or a feature collection.

A JSON-FG feature collection must contain a link to the JSON-FG feature collection schema at `\http://beta.schemas.opengis.net/json-fg/featurecollection.json`. Since the feature collection is is also a GeoJSON feature collection, it should also contain a link to the GeoJSON feature collection schema at `\https://geojson.org/schema/FeatureCollection.json`. The document should also contain another link to a schema document that specifies the properties of the features in the collection.

A JSON-FG feature must contain a link to the JSON-FG feature schema at `\http://beta.schemas.opengis.net/json-fg/feature.json`. Since the feature is is also a GeoJSON feature, it should also contain a link to the GeoJSON feature schema at `\https://geojson.org/schema/Feature.json`. The document should also contain another link to a schema document that specifies the properties of the feature.

NOTE: These are (or will be) canonical URIs. Clients can identify that a JSON document is a GeoJSON and JSON-FG feature collection or feature by string comparisons.

NOTE: #Check stability of the GeoJSON URIs with the GeoJSON maintainers.#

[NOTE]
====
#If features are accessed using building blocks from OGC API Features, a collection can be comprised of features with different feature types. The Features API SWG should include guidance in the Schema extension how to construct a feature schema for such a collection. Multiple options exist, including:#

- #A schema using "oneOf" with one set of properties for each feature type;#
- #A schema with a single properties object with the superset that all features conform to; and#
- #A separate schema per feature type.#
====

NOTE: #JSON Schema is a rich language and it should be considered to limit the language constructs that should be used in describing the properties in the feature schema. A potential starting point is the current proposal for https://docs.ogc.org/DRAFTS/19-079r1.html#rec_filter_queryables-schema[a JSON Schema profile for queryable feature properties].#

NOTE: #The schema of a feature type will typically specify the details of the feature properties, but it can also profile the feature-level members including the "geometry", "place" and "time" members. A typical example is to restrict the list of allowed geometry types. To simplify parsing the feature schemas it could be discussed, if canonical schemas for well-known types should be used in "$ref" members. For example, if the geometry is restricted to points, the "geometry" and "place" members could reference `\https://geojson.org/schema/Point.json` or some other canonical URI.#
