== Introduction

=== Motivation

JavaScript Object Notation (JSON) is a popular encoding format for geospatial data. The light weight, simple syntax, and clear human and machine readability of JSON as well as universal support in all modern programming languages appeals to developers. The GeoJSON format as defined in https://datatracker.ietf.org/doc/html/rfc7946[IETF RFC-7946] is a very popular encoding.  GeoJSON is supported by many commercial and open source geospatial techonology product and libraries.  GeoJSON is also supported in most deployments of APIs implementing the OGC API Features Standard. However, GeoJSON has limitations that prevent or limit its use in many cases, including:

* WGS 84 is the only allowed Coordinate Reference System (CRS);
* No support for metadata so such properties as the provenance of the data cannot be specified;
* No styling or symbology information is specified;
* Geometries are restricted to points, curves and surfaces with linear interpolation; and
* No general capability is available to specify the schema of a feature, its type or its temporal characteristics.

NOTE: PAV Comment.  I added Carl's comments about provenance metadata and styling information but I am not sure they are relevant here.  There is nothing preventing someone from adding additional members to GeoJSON to support these requirements.  They would simply be ignored by GeoJSON clients.  Also, I think these requirements are out-of-scope for the JSON-FG SWG.  The Metadata DWG (?) and the Styling/Symbology SWG (?) would need to consider extending GeoJSON with additional members to accommodate these requirements.

=== Scenarios

The following general scenarios are useful in understanding the principles were used in the JSON-FG design:

1. In order to display features in a 3D scene, a client accesses a Web API that shares a building dataset and that implements OGC API Features. The scene uses a projected CRS, such as `\http://www.opengis.net/def/crs/EPSG/0/5555`. The API advertises support for both GeoJSON and JSON-FG as feature representations and support for the projected CRS in addition to WGS 84.
2. A client accesses a JSON-FG file with building data that is stored locally or as a static file in the cloud (e.g., in an Object Storage or a GitHub repository). Again, the file is accessed to display features in a 3D scene and a time slider is used to suppress features outside of a user-specified time interval.

NOTE: The following descriptions use `application/vnd.ogc.fg+json` as the media type for JSON-FG.

==== Using a GeoJSON client

The client implementation only supports GeoJSON and not JSON-FG.  An assumption is that the client support CRS transforms.

In the first scenario (API access), the client requests the GeoJSON representation of the feature using `Accept: application/geo+json`. This is because the client only supports a GeoJSON feature encoding. The response will in general not include the JSON-FG extensions and is provided in WGS 84 with axis order longitude/latitude as the spatial CRS. The client will transform the geometry to the projected CRS.

In the second scenario (file access), the client has no access to a media type and has to inspect the file to determine if the file is a GeoJSON document that it can process. While the document is a JSON-FG document it is also a valid GeoJSON document.  Therefore, the client is still able to use and display the features. The client will, however, not understand the additional information introduced by JSON-FG. The avoid issues for GeoJSON clients parsing JSON-FG documents, the names of any JSON-FG extension members must not conflict with the names of existing GeoJSON members to avoid issues for GeoJSON clients parsing JSON-FG documents.

==== Using a JSON-FG client

The client implementation supports both GeoJSON and JSON-FG.

In the first scenario (API access), the client will typically request the JSON-FG representation of the feature using an HTTP header like `Accept: application/vnd.ogc.fg+json, application/geo+json;q=0.8` and a `crs=http://www.opengis.net/def/crs/EPSG/0/5555` query parameter. The header states that the client prefers JSON-FG, but if JONS-FG is not available will also accept GeoJSON. The response will include the headers `Content-Type: application/vnd.ogc.fg+json` as well as `Content-Crs: \http://www.opengis.net/def/crs/EPSG/0/5555` and include the JSON-FG building blocks including the geometry in the requested projected CRS and temporal information.

In the second scenario (file access), the JSON-FG client is in the same position as the GeoJSON client.  The client has no access to a media type and has to inspect the file to determine the type. The file could be GeoJSON, JSON-FG or some other kind of document that the client does not understand. JSON-FG documents include explicit declarations that conform to both GeoJSON and JSON-FG. Therefore, the client can identify the document as a JSON-FG document and process the content. Since the JSON-FG document provides spatial and temporal information about each feature, the client can zoom in on the features and, for example, provide a time slider so that the user can filter the features that are displayed.
