:req-class: circular_arcs
[#rc_{req-class}]
== Requirements Class "Circular Arcs"

The "Circular Arcs" Requirements Class adds provisions for curve geometries that may be of type <<CircularString>>, <<CompoundCurve>>, <<CurvePolygon>>, <<MultiCurve>>, or <<MultiSurface>>.

[cols="2,7",width="90%"]
|===
^|*Requirements Class* |http://www.opengis.net/spec/{standard}/{m_n}/req/{req-class} 
|Target type |JSON objects
|Dependency |<<rc_core>>
|===

=== Metadata

:req: metadata
[#{req-class}_{req}]
==== Conformance declaration

[width="90%",cols="2,7a"]
|===
^|*Requirement {counter:req-num}* |/req/{req-class}/{req}
^|A |The "conformsTo" member of a JSON-FG object that contains any of the curve geometry objects SHALL include at least the following value: `"http://www.opengis.net/spec/json-fg-1/{m_n}/conf/{req-class}"`.
|===

=== Geometry

:req: geom-valid
[#{req-class}_{req}]
==== Geometries are valid

[width="90%",cols="2,7a"]
|===
^|*Requirement {counter:req-num}* |/req/{req-class}/{req}
^|A |If the "place" member in any JSON-FG feature object is not `null` and the geometry type (member "type") is "CircularString", the elements in the "coordinates" array SHALL ... TODO.
^|B |If the "place" member in any JSON-FG feature object is not `null` and the geometry type (member "type") is "CompoundCurve", each element in the "geometries" array SHALL ... TODO.
^|C |If the "place" member in any JSON-FG feature object is not `null` and the geometry type (member "type") is "CurvePolygon", each element in the "geometries" array SHALL ... TODO.
^|D |If the "place" member in any JSON-FG feature object is not `null` and the geometry type (member "type") is "MultiCurve" or "MultiSurface", each element in the "geometries" array SHALL ... TODO.
|===
