:req-class: 3d
[#rc_{req-class}]
== Requirements Class "3D"

The Requirements Class "3D" add provisions for geometries in a 3D CRS and that may be a <<Polyhedron>>, <<MultiPolyhedron>>, <<Prism>> or <<MultiPrism>>.

[cols="2,7",width="90%"]
|===
^|*Requirements Class* |http://www.opengis.net/spec/{standard}/{m_n}/req/{req-class} 
|Target type |JSON documents
|Dependency |<<rc_core>>
|===

=== Geometry

:req: coordinate-dimension
[#{req-class}_{req}]
==== Coordinate dimension

[width="90%",cols="2,7a"]
|===
^|*Requirement {counter:req-num}* |/req/{req-class}/{req}
^|A |All positions in a geometry object in the "place" member in any JSON-FG feature in the JSON document SHALL have coordinate dimension 3.
|===

:req: geom-valid
[#{req-class}_{req}]
==== Geometries are valid

[width="90%",cols="2,7a"]
|===
^|*Requirement {counter:req-num}* |/req/{req-class}/{req}
^|A |If the "place" member in any JSON-FG feature in the JSON document is not `null` and the geometry type (member "type") is "Polyhedron", the elements in the "coordinates" array SHALL meet the following requirements:

* Each element is a closed, simple multi-polygon geometry (a shell).
* The orientation of each polygon in the first element (the outer shell) SHALL be counter-clockwise, if the shell is viewed from the outside of the solid.
* The orientation of each polygon in all other shells (the voids) SHALL be clockwise, if the shell is viewed from the outside of the solid.
* No element (shell) intersects another element (shell).
* All coordinates in the second to last element (the voids) are inside the simple polyhedron specified by the first element (the outer shell).
* In the second to last elements (the voids) there is no element where all coordinates of the element are inside the simple polyhedron specified by another element (no void contains another void).
^|B |If the "place" member in any JSON-FG feature in the JSON document is not `null` and the geometry type (member "type") is "MultiPolyhedron", each element in the "coordinates" array SHALL be a valid polyhedron geometry (see A).
^|C |If the "place" member in any JSON-FG feature in the JSON document is not `null` and the geometry type (member "type") is "Prism", the base geometry (member "base") SHALL be one of "Point", "MultiPoint", "LineString", "MultiLineString", "Polygon" or "MultiPolygon", and geometry object SHALL be a valid geometry according to <<ogc06_103r4,Simple feature access - Part 1: Common architecture>>.
^|D |If the "place" member in any JSON-FG feature in the JSON document is not `null` and the geometry type (member "type") is "MultiPrism", each prism (items in the member "prisms") SHALL be valid Prism geometry.
|===

NOTE: It is recommended that clients should, if possible, be tolerant and also accept shells with an incorrect orientation.
