:req-class: profiles
[#rc_{req-class}]
== Requirements Class "GeoJSON Profiles"

The Requirements Class "GeoJSON Profiles" adds provisions for three GeoJSON profiles.

[cols="2,7",width="90%"]
|===
^|*Requirements Class* |http://www.opengis.net/spec/{standard}/{m_n}/req/{req-class} 
|Target type |JSON documents
|Conditional Dependency |<<rfc7946,RFC 7946: The GeoJSON Format>>
|Conditional Dependency |<<rc_core>>
|===

[[profile-rfc7946]]
=== Profile "RFC 7946"

:req: rfc7946
[width="90%",cols="2,7a"]
|===
^|*Requirement {counter:req-num}* |/req/{req-class}/{req}
^|Condition |A JSON document has a link to the profile "\http://www.opengis.net/def/profile/OGC/0/{req}".
^|A |The JSON document SHALL conform to <<rfc7946,RFC 7946 (The GeoJSON Format)>>.
^|B |The JSON document SHALL not include a JSON-FG conformance class URI in the "conformsTo" member, if one is provided.
^|C |The JSON document SHALL not include a "place" member in any feature object.
|===

:per: rfc7946
[width="90%",cols="2,7a"]
|===
^|*Permission {counter:per-num}* |/per/{req-class}/{per}
^|Condition |A JSON document has a link to the profile "\http://www.opengis.net/def/profile/OGC/0/{req}".
^|A |The JSON document MAY include coordinates in the "geometry" member that are not in WGS 84, if a prior arrangement exists (that is, by explicitly requesting the use of the coordinate reference system when generating the JSON document).
|===

[[profile-jsonfg]]
=== Profile "JSON-FG"

:req: jsonfg
[width="90%",cols="2,7a"]
|===
^|*Requirement {counter:req-num}* |/req/{req-class}/{req}
^|Condition |A JSON document has a link to the profile "\http://www.opengis.net/def/profile/OGC/0/{req}".
^|A |The JSON document SHALL conform to the <<rc_core,Requirements Class "Core">>.
|===

[[profile-jsonfg-plus]]
=== Profile "JSON-FG with improved GeoJSON support"

:req: jsonfg-plus
[width="90%",cols="2,7a"]
|===
^|*Requirement {counter:req-num}* |/req/{req-class}/{req}
^|Condition |A JSON document has a link to the profile "\http://www.opengis.net/def/profile/OGC/0/{req}".
^|A |The JSON document SHALL conform to the <<rc_core,Requirements Class "Core">>.
^|B |Each feature in the JSON document SHALL include a non-null "geometry" member, if the feature has a non-null "place" member.
|===
