== Conventions

=== Identifiers
The normative provisions in this Standard are denoted by the URI

`\http://www.opengis.net/spec/{standard}/{m_n}`

All requirements and conformance tests that appear in this document are denoted by partial URIs which are relative to this base.

=== Use of JSON Schema

JSON Schema is used to formally specify the JSON-FG syntax, where possible. Additional requirements are only used where it is not possible to express the requirement in JSON Schema or where this would result in a schema that is considered as too complex. All schemas are in Annex '<<schemas>>'.

=== Use of CURIEs

This document uses link:https://www.w3.org/TR/curie/[CURIEs] (Compact URIs) as a compact notation of URIs, in particular for URIs of coordinate reference systems.

NOTE: The draft policy for using CURIEs in OGC standards is documented https://portal.ogc.org/files/?artifact_id=100119&version=#toc14[here]. Once the updated policy has been published, this note will be converted to regular text.

=== Extensibility

JSON-FG has been designed to be extensible. Extensions can be specified in revisions to this Standard, in additional parts of JSON-FG or by a community.

Readers of JSON-FG documents should therefore be prepared to process documents with unknown members or with known members, but unknown value types. Unknown members should be ignored. Values of a known member with an unknown value type should be mapped to `null`.

The JSON schemas have been designed to support extensions. JSON-FG documents that include extensions will still validate against the JSON-FG schemas.

The "$id" member of the schemas does not include information about the version of the Standard or the part of the JSON-FG standard. Future revisions of this Standard or additional parts of JSON-FG will update and extend the JSON-FG schemas. Any change will not invalidate existing JSON-FG documents.

<add an Annex with examples how future parts or communities can extend the schemas>