== Conformance
This Standard defines eight requirements classes.

Six requirements classes have JSON objects as their standardization target type:

* "Core": The _Core_ requirements class extends GeoJSON with additional members that specify how <<time,temporal information>>, extended <<place,geometry information>>, and <<ref-sys,coordinate reference system information>> can be encoded in a JSON-FG object. In addition, <<metadata,metadata>> is added to declare the JSON-FG conformance classes that a JSON object conforms to. The _Core_ requirements class has a dependency on GeoJSON. This means that a JSON-FG object that conforms to _Core_ must also conform to GeoJSON.

* "Polyhedra": The _Polyhedra_ requirements class adds support for <<Polyhedron>> and <<MultiPolyhedron>> geometries in a 3D CRS. The _Polyhedra_ requirements class has a dependency on the _Core_ requirements class. This means that a JSON-FG object that conforms to the _Polyhedra_ conformance class must also conform to the _Core_ conformance class.

* "Prisms": The _Prisms_ requirements class adds support for <<Prism>>, and <<MultiPrism>> geometries in a 3D CRS.  The _Prisms_ requirements class has a dependency on the _Core_ requirements class. This means that a JSON-FG object that conforms to the _Prisms_ conformance class must also conform to the _Core_ conformance class.

* "Circular Arcs": The _Circular Arcs_ requirements class adds support for <<CircularString>>, <<CompoundCurve>>, <<CurvePolygon>>, <<MultiCurve>>, and <<MultiSurface>> geometries to support curves with linear and circular arc interpolation. The _Circular Arcs_ requirements class has a dependency on the _Core_ requirements class. This means that a JSON-FG object that conforms to the _Circular Arcs_ conformance class must also conform to the _Core_ conformance class.

* "Measures": The _Measures_ requirements class adds support for the <<measures>> member and measure values in coordinates. The _Measures_ requirements class has a dependency on the _Core_ requirements class. This means that a JSON-FG object that conforms to the _Measures_ conformance class must also conform to the _Core_ conformance class.

* "Feature Types and Schemas": The _Feature Types and Schemas_ requirements class adds support for <<feature-types,feature types>> and <<schema-ref,schema references>>. Features are often categorized by type. This requirements class adds members to a JSON-FG feature or feature collection so that contained features can be tagged with a type value.  This requirements class includes guidance about how to include information about the schema of a feature type. The _Feature Types and Schemas_ requirements class has a dependency on the _Core_ requirements class. This means that a JSON-FG object that conforms to the _Feature Types and Schemas_ conformance class must also conform to the _Core_ conformance class.

The seventh requirements class, "GeoJSON Profiles", has GeoJSON documents as its standardization type. The requirements class adds support for <<profiles>> of the GeoJSON media type. The _GeoJSON Profiles_ requirements class has conditional dependencies on GeoJSON and the _Core_ requirements class. 

The eighth requirements class, "JSON-FG in Web APIs", has Web APIs as its standardization target type. The requirements class specifies how clients can request GeoJSON in the JSON-FG profiles via a Web API.

Conformance with the JSON-FG Standard shall be checked using all the relevant tests specified in Annex A (normative) of this document. The framework, concepts, and methodology for testing, and the criteria to be achieved to claim conformance are specified in the OGC Compliance Testing Policies and Procedures and the OGC Compliance Testing web site.

In order to conform to this OGC® Standard, a software implementation shall choose to implement one or more of the conformance levels specified in Annex A (normative).

All requirements-classes and conformance-classes described in this document are owned by the Standard(s) identified.

[#conf_class_uris,reftext='{table-caption} {counter:table-num}']
.Conformance class URIs
[cols="40,60",options="header"]
!===
|Conformance class |URI
|<<conf_core,Core>> |http://www.opengis.net/spec/{standard}/{m_n}/conf/core
|<<conf_polyhedra,Polyhedra>> |http://www.opengis.net/spec/{standard}/{m_n}/conf/polyhedra
|<<conf_prisms,Prisms>> |http://www.opengis.net/spec/{standard}/{m_n}/conf/risms
|<<conf_circular-arcs,Circular Arcs>> |http://www.opengis.net/spec/{standard}/{m_n}/conf/circular-arcs
|<<conf_measures,Measures>> |http://www.opengis.net/spec/{standard}/{m_n}/conf/measures
|<<conf_types-schemas,Feature Types and Schemas>> |http://www.opengis.net/spec/{standard}/{m_n}/conf/types-schemas
|<<conf_profiles,GeoJSON Profiles>> |http://www.opengis.net/spec/{standard}/{m_n}/conf/profiles
|<<conf_api,JSON-FG in Web APIs>> |http://www.opengis.net/spec/{standard}/{m_n}/conf/api
!===
