:req-class: circular-arcs
[#rc_{req-class}]
== Requirements Class "Circular Arcs"

The "Circular Arcs" Requirements Class adds provisions for curve geometries that may be of type <<CircularString>>, <<CompoundCurve>>, <<CurvePolygon>>, <<MultiCurve>>, or <<MultiSurface>>.

[cols="2,7",width="90%"]
|===
^|*Requirements Class* |http://www.opengis.net/spec/{standard}/{m_n}/req/{req-class} 
|Target type |JSON-FG root objects
|Dependency |<<rc_core>>
|===

=== Metadata

:req: metadata
[#{req-class}_{req}]
==== Conformance declaration

[width="90%",cols="2,7a"]
|===
^|*Requirement {counter:req-num}* |/req/{req-class}/{req}
^|A |The "conformsTo" member of the JSON-FG root object SHALL include the value `"http://www.opengis.net/spec/json-fg-1/{m_n}/conf/{req-class}"`.
|===

=== Geometry

:req: valid-geometry
[#{req-class}_{req}]
==== Geometries are valid

[width="90%",cols="2,7a"]
|===
^|*Requirement {counter:req-num}* |/req/{req-class}/{req}
^|A |In any JSON-FG geometry of type "CircularString", the items in the "coordinates" array SHALL meet the following requirements:

* The items are a sequence of one, two, three, four, or five connected circular arcs, where each arc is a sequence of three positions and the first position of each connected arc is not repeated (that is, the circular string consists of three, five, seven, nine, or eleven positions);
* The first, second and third position of each circular arc are all different;
* The first, second and third position of each circular arc are not collinear.
^|B |In any JSON-FG geometry of type "CompoundCurve", each item in the "geometries" array except the first item SHALL meet the following requirement:

* The first position of each item is identical to the last position of the previous item (that is, all items are consequtive).
^|C |In any JSON-FG geometry of type "CurvePolygon", each item in the "geometries" array SHALL meet the following requirement:

* The first and last position of each curve geometry is identical  (that is, each item is a closed ring).
|===

NOTE: The valid geometry items in the "CompoundCurve", "CurvePolygon", "MultiCurve", and "MultiSurface" geometries are implicitly specified by the JSON Schema for the JSON-FG geometries.
