:req-class: polyhedra
[#rc_{req-class}]
== Requirements Class "Polyhedra"

[cols="2,7",width="90%"]
|===
^|*Requirements Class* |http://www.opengis.net/spec/{standard}/{m_n}/req/{req-class} 
|Target type |JSON objects
|Dependency |<<rc_core>>
|===

The "Polyhedra" Requirements Class adds provisions for volumetric geometries in a 3D CRS that may be of type <<Polyhedron>> or <<MultiPolyhedron>>.

=== Metadata

:req: metadata
[#{req-class}_{req}]
==== Conformance declaration

[width="90%",cols="2,7a"]
|===
^|*Requirement {counter:req-num}* |/req/{req-class}/{req}
^|A |The "conformsTo" member of a JSON-FG root object that contains any of the polyhedron geometry types SHALL include the value `"http://www.opengis.net/spec/json-fg-1/{m_n}/conf/{req-class}"`.
|===

=== Geometry

:req: coordinates
[#{req-class}_{req}]
==== Coordinates

[width="90%",cols="2,7a"]
|===
^|*Requirement {counter:req-num}* |/req/{req-class}/{req}
^|A |All positions in a "Polyhedron" or "MultiPolyhedron" geometry in the "place" member in any JSON-FG feature SHALL have a coordinate dimension of three (3) - or four (4), if measure values are included (see <<rc_measures>>).
^|B |The CRS of each Polyhedron geometry SHALL be have three dimensions (a 3D CRS or an ad-hoc compound CRS consisting of a horizontal 2D CRS and a vertical CRS).
|===

:req: geom-valid
[#{req-class}_{req}]
==== Geometries are valid

[width="90%",cols="2,7a"]
|===
^|*Requirement {counter:req-num}* |/req/{req-class}/{req}
^|A |If the "place" value in any JSON-FG feature is not `null` and the geometry type (member "type") is "Polyhedron", the elements in the "coordinates" array SHALL meet the following requirements:

* Each element is a closed, simple multi-polygon geometry (a shell).
* The coordinates of the first and last position in each ring of each polygon in each shell SHALL be identical.
* If the shell is viewed from the outside of the solid, the orientation of each polygon in the first element (the outer shell) SHALL be counter clockwise.
* If the shell is viewed from the outside of the solid, the orientation of each polygon in all other shells (the voids) SHALL be clockwise.
* No element (shell) intersects another element (shell).
* All coordinates in the elements from the second element to the last element (the voids) are inside the simple polyhedron specified by the first element (the outer shell).
* In the elements from the second element to the last element (the voids) there is no element where all coordinates of the element are inside the shell specified by another element (no void contains another void).
^|B |If the "place" member in any JSON-FG feature is not `null` and the geometry type (member "type") is "MultiPolyhedron", each element in the "coordinates" array SHALL be a valid polyhedron geometry (see A).
|===

Clients should, if possible, be tolerant and also accept shells with an incorrect orientation.
