== Conformance
This Standard defines three requirements classes. 

The standardization target for all requirements classes are JSON documents.

Requirements for three standardization target types are considered:

* "Core": Support for <<when>>, <<where>> and <<ref-sys>>, except support for <<Polyhedron>> and <<MultiPolyhedron>>. Depends on GeoJSON.
* "3D": Geometries are in a 3D CRS and may be a <<Polyhedron>> or <<MultiPolyhedron>>. Depends on "Core".
* "Feature Types and Schemas": Support for <<feature-types>> and <<schema-ref>>. Depends on "Core".

Implementations must support at least the Core requirements class to use the JSON-FG media type.

Conformance with this Standard shall be checked using all the relevant tests specified in Annex A (normative) of this document. The framework, concepts, and methodology for testing, and the criteria to be achieved to claim conformance are specified in the OGC Compliance Testing Policies and Procedures and the OGC Compliance Testing web site.

In order to conform to this OGC® Standard, a software implementation shall choose to implement one or more of the conformance levels specified in Annex A (normative).

All requirements-classes and conformance-classes described in this document are owned by the Standard(s) identified.
