= Circular geometry objects

Version: 0.1.0

== Overview

GeoJSON uses the seven concrete geometry types defined in link:https://portal.ogc.org/files/?artifact_id=829[99-049 OpenGIS Simple Features Specification For SQL Rev 1.1], which all use linear interpolation between positions.

A number of national standards, including the Dutch link:https://www.geonovum.nl/geo-standaarden/bgt-imgeo[Basisregistratie Grootschalige Topografie], include the use of circular interpolation between positions, i.e. arcs and circles. Exchanging these geometries is done using _GML Simple Features profile level 2_ (SF2).

Adding geometry types with circular interpolation to JSON-FG will make JSON-FG a suitable replacement for GML SF2 when designing API's and systems where arcs and circles must be supported.

There are two main approaches for adding arcs and circles to JSON-FG:

1. link:https://portal.ogc.org/files/?artifact_id=20509[07-036 GML 3.2.1] encodes support for arcs and circles in existing objects. For example the exterior ring of a _Polygon_ can be either a _LinearRing_ or a _Ring_, where the latter can have _Curves_ and _LineStrings_.

2. Well-known Binary (WKB) as defined in link:https://portal.ogc.org/files/?artifact_id=25355[06-103r4 OpenGIS Implementation Specification for Geographic information - Simple feature access - Part 1: Common architecture] adds support for arcs and circles by defining new geometry types which coexist with existing linear interpolation geometry types.

The first approach cannot be applied to JSON-FG since it would confict with the geometry types used by GeoJSON. For example a _Polygon_ defined by JSON-FG would differ from the _Polygon_ defined by GeoJSON. The second approach is better suited and is used in this proposal.

Another limitation imposed by GeoJSON is that a _GeometryCollection_ cannot be extended to include new geometry types, which requires the introduction of a new collection type.

Other noteworthy points found in the GML and WKB standards:

* GML defines different types of arcs (_circular arc by three points_, _circular arc by two points and bulge factor_, etc.) of which _circular arc by three points_ is the most suited. It also matches how surveying in the field is done.

* GML defines a circle by three positions, which makes it possible to assign the circle a direction.

* WKB defines a circle by three positions where the first and last positions are equivalent. This has the advantage of defining a circle as a closed ring, but the circle lacks a direction.

* WKB can encode consecutive arcs more efficient than GML. For example for 3 consecutive arcs GML would need 3 curve segments with 3 positions each, WKB can encode this with a _CircularString_ using 7 positions.

* The naming of curve geometries in WKB is not consistent. For example a polygon where a ring is of type _CompoundCurve_ is named a _CurvePolygon_, but a collection of such polygons is named _MultiSurface_.

The following geometry types are introduced to support circular interpolation:

* Arc
* Circle
* CompoundCurve
* MultiCompoundCurve
* CurvePolygon
* MultiCurvePolygon
* CurveGeometryCollection

== Examples

Note that all examples use RD new (http://www.opengis.net/def/crs/EPSG/0/28992) as the CRS.

The following example is an _Arc_ geometry.

[#example_arc,reftext='{listing-caption} {counter:listing-num}']
.Arc geometry
[%collapsible]
====
[source,json,linenumbers]
----
{
  "type": "Arc",
  "coordinates": [
    [96101.000, 400603.000],
    [96102.000, 400604.000],
    [96103.000, 400603.000]
  ]
}
----
====

The next example is a _Circle_ geometry.

[#example_circle,reftext='{listing-caption} {counter:listing-num}']
.Circle geometry
[%collapsible]
====
[source,json,linenumbers]
----
{
  "type": "Circle",
  "coordinates": [
    [96103.337, 400611.390],
    [96104.822, 400616.074],
    [96110.480, 400613.523],
    [96103.337, 400611.390]
  ]
}
----
====

The next example shows an _Arc_ used in a _CompoundCurve_ geometry.

[#example_compoundcurve,reftext='{listing-caption} {counter:listing-num}']
.CompoundCurve geometry
[%collapsible]
====
[source,json,linenumbers]
----
{
  "type": "CompoundCurve",
  "coordinates": [
    {
      "type": "LineString",
      "coordinates": [
        [96101.000, 400604.000],
        [96101.000, 400605.000]
      ]
    },
    {
      "type": "Arc",
      "coordinates": [
        [96101.000, 400605.000],
        [96102.000, 400606.000],
        [96103.000, 400605.000]
      ]
    },
    {
      "type": "LineString",
      "coordinates": [
        [96103.000, 400605.000],
        [96104.000, 400605.000]
      ]
    },
    {
      "type": "Arc",
      "coordinates": [
        [96104.000, 400605.000],
        [96105.000, 400604.000],
        [96106.000, 400605.000]
      ]
    }
  ]
}
----
====

The example below shows a _MultiCompoundCurve_ geometry which is a collection of _CompoundCurve_ geometries.

[#example_multicompoundcurve,reftext='{listing-caption} {counter:listing-num}']
.MultiCompoundCurve geometry
[%collapsible]
====
[source,json,linenumbers]
----
{
  "type": "MultiCompoundCurve",
  "coordinates": [
    {
      "type": "CompoundCurve",
      "coordinates": [
        {
          "type": "LineString",
          "coordinates": [
            [96125.000, 400600.000],
            [96127.000, 400601.000],
            [96127.000, 400602.000]
          ]
        }
      ]
    },
    {
      "type": "CompoundCurve",
      "coordinates": [
        {
          "type": "Arc",
          "coordinates": [
            [96125.000, 400602.000],
            [96125.000, 400603.000],
            [96126.000, 400603.000]
          ]
        },
        {
          "type": "Arc",
          "coordinates": [
            [96126.000, 400603.000],
            [96127.000, 400603.000],
            [96127.000, 400604.000]
          ]
        }
      ]
    }
  ]
}
----
====

The following example shows a _CurvePolygon_ geometry which uses _CompoundCurve_ geometries for its rings.

[#example_curvepolygon,reftext='{listing-caption} {counter:listing-num}']
.CurvePolygon geometry
[%collapsible]
====
[source,json,linenumbers]
----
{
  "type": "CurvePolygon",
  "coordinates": [
    {
      "type": "CompoundCurve",
      "coordinates": [
        {
          "type": "LineString",
          "coordinates": [
            [96116.000, 400607.000],
            [96118.000, 400607.000]
          ]
        },
        {
          "type": "Arc",
          "coordinates": [
            [96118.000, 400607.000],
            [96120.000, 400608.000],
            [96121.000, 400610.000]
          ]
        },
        {
          "type": "Arc",
          "coordinates": [
            [96121.000, 400610.000],
            [96120.000, 400612.000],
            [96118.000, 400613.000]
          ]
        },
        {
          "type": "LineString",
          "coordinates": [
            [96118.000, 400613.000],
            [96116.000, 400613.000]
          ]
        },
        {
          "type": "Arc",
          "coordinates": [
            [96116.000, 400613.000],
            [96114.000, 400612.000],
            [96113.000, 400610.000]
          ]
        },
        {
          "type": "Arc",
          "coordinates": [
            [96113.000, 400610.000],
            [96114.000, 400608.000],
            [96116.000, 400607.000]
          ]
        }
      ]
    },
    {
      "type": "CompoundCurve",
      "coordinates": [
        {
          "type": "Circle",
          "coordinates": [
            [96118.000, 400611.000],
            [96118.000, 400612.000],
            [96119.000, 400612.000],
            [96118.000, 400611.000]
          ]
        }
      ]
    },
    {
      "type": "CompoundCurve",
      "coordinates": [
        {
          "type": "LineString",
          "coordinates": [
            [96116.000, 400608.000],
            [96116.000, 400609.000]
          ]
        },
        {
          "type": "Arc",
          "coordinates": [
            [96116.000, 400609.000],
            [96117.000, 400610.000],
            [96119.000, 400610.000]
          ]
        },
        {
          "type": "LineString",
          "coordinates": [
            [96119.000, 400610.000],
            [96119.000, 400609.000]
          ]
        },
        {
          "type": "Arc",
          "coordinates": [
            [96119.000, 400609.000],
            [96118.000, 400608.000],
            [96116.000, 400608.000]
          ]
        }
      ]
    },
    {
      "type": "CompoundCurve",
      "coordinates": [
        {
          "type": "Arc",
          "coordinates": [
            [96116.000, 400611.000],
            [96116.000, 400612.000],
            [96117.000, 400612.000]
          ]
        },
        {
          "type": "Arc",
          "coordinates": [
            [96117.000, 400612.000],
            [96117.000, 400611.000],
            [96116.000, 400611.000]
          ]
        }
      ]
    },
    {
      "type": "CompoundCurve",
      "coordinates": [
        {
          "type": "LineString",
          "coordinates": [
            [96114.000, 400609.000],
            [96114.000, 400611.000],
            [96115.000, 400609.000],
            [96114.000, 400609.000]
          ]
        }
      ]
    }
  ]
}
----
====

The example below shows a _MultiCurvePolygon_ geometry which is a collection of _CurvePolygon_ geometries.

[#example_multicurvepolygon,reftext='{listing-caption} {counter:listing-num}']
.MultiCurvePolygon geometry
[%collapsible]
====
[source,json,linenumbers]
----
{
  "type": "MultiCurvePolygon",
  "coordinates": [
    {
      "type": "CurvePolygon",
      "coordinates": [
        {
          "type": "CompoundCurve",
          "coordinates": [
            {
              "type": "Arc",
              "coordinates": [
                [96134.000, 400603.000],
                [96135.000, 400601.000],
                [96137.000, 400600.000]
              ]
            },
            {
              "type": "LineString",
              "coordinates": [
                [96137.000, 400600.000],
                [96139.000, 400600.000]
              ]
            },
            {
              "type": "Arc",
              "coordinates": [
                [96139.000, 400600.000],
                [96141.000, 400601.000],
                [96142.000, 400603.000]
              ]
            },
            {
              "type": "Arc",
              "coordinates": [
                [96142.000, 400603.000],
                [96141.000, 400605.000],
                [96139.000, 400606.000]
              ]
            },
            {
              "type": "LineString",
              "coordinates": [
                [96139.000, 400606.000],
                [96137.000, 400606.000]
              ]
            },
            {
              "type": "Arc",
              "coordinates": [
                [96137.000, 400606.000],
                [96135.000, 400605.000],
                [96134.000, 400603.000]
              ]
            }
          ]
        }
      ]
    },
    {
      "type": "CurvePolygon",
      "coordinates": [
        {
          "type": "CompoundCurve",
          "coordinates": [
            {
              "type": "LineString",
              "coordinates": [
                [96135.000, 400609.000],
                [96135.000, 400611.000],
                [96136.000, 400609.000],
                [96135.000, 400609.000]
              ]
            }
          ]
        }
      ]
    }
  ]
}
----
====

And finally an example of a _CurveGeometryCollection_ geometry which is a heterogeneous collection like _GeometryCollection_, but extended to include circular geometry objects.

[#example_curvegeometrycollection,reftext='{listing-caption} {counter:listing-num}']
.CurveGeometryCollection geometry
[%collapsible]
====
[source,json,linenumbers]
----
{
  "type": "CurveGeometryCollection",
  "geometries": [
    {
      "type": "Point",
      "coordinates": [96144.000, 400601.000]
    },
    {
      "type": "Polygon",
      "coordinates": [
        [
          [96144.000, 400602.000],
          [96145.000, 400600.000],
          [96147.000, 400600.000],
          [96149.000, 400602.000],
          [96149.000, 400603.000],
          [96144.000, 400603.000],
          [96144.000, 400602.000]
        ],
        [
          [96146.000, 400602.000],
          [96148.000, 400602.000],
          [96147.000, 400601.000],
          [96146.000, 400601.000],
          [96146.000, 400602.000]
        ]
      ]
    },
    {
      "type": "CompoundCurve",
      "coordinates": [
        {
          "type": "Arc",
          "coordinates": [
            [96144.000, 400606.000],
            [96145.000, 400605.000],
            [96146.000, 400606.000]
          ]
        },
        {
          "type": "Arc",
          "coordinates": [
            [96144.000, 400606.000],
            [96145.000, 400605.000],
            [96146.000, 400606.000]
          ]
        },
        {
          "type": "Arc",
          "coordinates": [
            [96148.000, 400606.000],
            [96148.000, 400605.000],
            [96149.000, 400606.000]
          ]
        }
      ]
    },
    {
      "type": "CurvePolygon",
      "coordinates": [
        {
          "type": "CompoundCurve",
          "coordinates": [
            {
              "type": "Arc",
              "coordinates": [
                [96147.000, 400609.000],
                [96148.000, 400610.000],
                [96149.000, 400612.000]
              ]
            },
            {
              "type": "Arc",
              "coordinates": [
                [96149.000, 400612.000],
                [96148.037, 400614.011],
                [96147.000, 400615.000]
              ]
            },
            {
              "type": "Arc",
              "coordinates": [
                [96147.000, 400615.000],
                [96145.000, 400615.000],
                [96144.000, 400613.000]
              ]
            },
            {
              "type": "LineString",
              "coordinates": [
                [96144.000, 400613.000],
                [96144.000, 400609.000],
                [96147.000, 400609.000]
              ]
            }
          ]
        },
        {
          "type": "CompoundCurve",
          "coordinates": [
            {
              "type": "Circle",
              "coordinates": [
                [96118.000, 400611.000],
                [96118.000, 400612.000],
                [96119.000, 400612.000],
                [96118.000, 400611.000]
              ]
            }
          ]
        },
        {
          "type": "CompoundCurve",
          "coordinates": [
            {
              "type": "Arc",
              "coordinates": [
                [96145.000, 400614.000],
                [96146.000, 400614.000],
                [96146.000, 400613.000]
              ]
            },
            {
              "type": "Arc",
              "coordinates": [
                [96146.000, 400613.000],
                [96145.000, 400612.000],
                [96145.000, 400614.000]
              ]
            }
          ]
        }
      ]
    }
  ]
}
----
====

== Description

=== Arc

An _Arc_ consists of 3 positions with circular interpolation being used between positions. It starts at the first position, goes through the second position and ends at the third position.

=== Circle

A _Circle_ consists of 4 positions with circular interpolation being used between positions. It starts at the first position, goes through the second position, followed by the third position and ends at the fourth position. The first and fourth position must be equivalent, which requires the _Circle_ to be closed.

The coordinates of the second and third position determine the direction of the _Circle_.

=== CompoundCurve

A _CompoundCurve_ is a curve which consists of one or more segments. Each segment can be a _LineString_, _Arc_, or _Circle_.

The first position of the each segment must be equivalent to the last position of the previous segment, except for the first position of the first segment.

If the last position of the last segment is equivalent to the first position of the first segment the _CompoundCurve_ is closed.

=== MultiCompoundCurve

A _MultiCompoundCurve_ is a homogeneous collection of _CompoundCurve_ geometries.

=== CurvePolygon

A _CurvePolygon_ is a polygon where each ring (exterior and interior) is a _CompoundCurve_ geometry. Each _CompoundCurve_ must be closed.

=== MultiCurvePolygon

A _MultiCurvePolygon_ is a homogeneous collection of _CurvePolygon_ geometries.

=== CurveGeometryCollection

A _CurveGeometryCollection_ is a heterogeneous collection of geometries. The following geometry types can be added to a _CurveGeometryCollection_:

* Point
* MultiPoint
* LineString
* MultiLineString
* Polygon
* MultiPolygon
* Arc
* Circle
* CompoundCurve
* MultiCompoundCurve
* CurvePolygon
* MultiCurvePolygon

=== JSON schema

The JSON schema below describes the new geometry types.

[#jsonschema_circulargeometryobjects,reftext='{listing-caption} {counter:listing-num}']
.JSON Schema for circular geometry objects
[%collapsible]
====
[source,json,linenumbers]
----
{
  "$schema": "https://json-schema.org/draft/2019-09/schema",
  "$id": "http://beta.schemas.opengis.net/json-fg/circular-geometry-objects.json",
  "title": "Circular geometry objects",
  "$defs": {
    "Arc": {
      "title": "JSON-FG Arc",
      "type": "object",
      "required": ["type", "coordinates"],
      "properties": {
        "type": {
          "type": "string",
          "enum" : ["Arc"]
        },
        "coordinates": {
          "type": "array",
          "minItems": 3,
          "maxItems": 3,
          "items": {
            "$ref": "geometry-objects.json#/$defs/position"
          }
        },
        "bbox": {
          "$ref": "geometry-objects.json#/$defs/bbox"
        }
      }
    },
    "Circle": {
      "title": "JSON-FG Circle",
      "type": "object",
      "required": ["type", "coordinates"],
      "properties": {
        "type": {
          "type": "string",
          "enum": ["Circle"]
        },
        "coordinates": {
          "type": "array",
          "minItems": 4,
          "maxItems": 4,
          "items": {
            "$ref": "geometry-objects.json#/$defs/position"
          }
        },
        "bbox": {
          "$ref": "geometry-objects.json#/$defs/bbox"
        }
      }
    },
    "CompoundCurve": {
      "title": "JSON-FG CompoundCurve",
      "type": "object",
      "required": ["type", "coordinates"],
      "properties": {
        "type": {
          "type": "string",
          "enum": ["CompoundCurve"]
        },
        "coordinates": {
          "type": "array",
          "minItems": 1,
          "items": {
            "oneOf": [
              {
                "$ref": "#/$defs/Arc"
              },
              {
                "$ref": "#/$defs/Circle"
              },
              {
                "$ref": "geometry-objects.json#/$defs/LineString"
              }
            ]
          }
        },
        "bbox": {
          "$ref": "geometry-objects.json#/$defs/bbox"
        }
      }
    },
    "MultiCompoundCurve": {
      "title": "JSON-FG MultiCompoundCurve",
      "type": "object",
      "required": ["type", "coordinates"],
      "properties": {
        "type": {
          "type": "string",
          "enum": ["MultiCompoundCurve"]
        },
        "coordinates": {
          "type": "array",
          "items": {
            "$ref": "#/$defs/CompoundCurve"
          }
        },
        "bbox": {
          "$ref": "geometry-objects.json#/$defs/bbox"
        }
      }
    },
    "CurvePolygon": {
      "title": "JSON-FG CurvePolygon",
      "type": "object",
      "required": ["type", "coordinates"],
      "properties": {
        "type": {
          "type": "string",
          "enum": ["CurvePolygon"]
        },
        "coordinates": {
          "type": "array",
          "minItems": 1,
          "items": {
            "$ref": "#/$defs/CompoundCurve"
          }
        },
        "bbox": {
          "$ref": "geometry-objects.json#/$defs/bbox"
        }
      }
    },
    "MultiCurvePolygon": {
      "title": "JSON-FG MultiCurvePolygon",
      "type": "object",
      "required": ["type", "coordinates"],
      "properties": {
        "type": {
          "type": "string",
          "enum": ["MultiCurvePolygon"]
        },
        "coordinates": {
          "type": "array",
          "items": {
            "$ref": "#/$defs/CurvePolygon"
          }
        },
        "bbox": {
          "$ref": "geometry-objects.json#/$defs/bbox"
        }
      }
    },
    "CurveGeometryCollection": {
      "title": "JSON-FG CurveGeometryCollection",
      "type": "object",
      "required": ["type", "geometries"],
      "properties": {
        "type": {
          "type": "string",
          "enum": ["CurveGeometryCollection"]
        },
        "geometries": {
          "type": "array",
          "items": {
            "oneOf": [
              {
                "$ref": "geometry-objects.json#/$defs/Point"
              },
              {
                "$ref": "geometry-objects.json#/$defs/MultiPoint"
              },
              {
                "$ref": "geometry-objects.json#/$defs/LineString"
              },
              {
                "$ref": "geometry-objects.json#/$defs/MultiLineString"
              },
              {
                "$ref": "geometry-objects.json#/$defs/Polygon"
              },
              {
                "$ref": "geometry-objects.json#/$defs/MultiPolygon"
              },
              {
                "$ref": "#/$defs/Arc"
              },
              {
                "$ref": "#/$defs/Circle"
              },
              {
                "$ref": "#/$defs/CompoundCurve"
              },
              {
                "$ref": "#/$defs/MultiCompoundCurve"
              },
              {
                "$ref": "#/$defs/CurvePolygon"
              },
              {
                "$ref": "#/$defs/MultiCurvePolygon"
              }
            ]
          }
        },
        "bbox": {
          "$ref": "geometry-objects.json#/$defs/bbox"
        }
      }
    }
  }
}
----
====

== Discussion, Alternatives, References

* Another common definition for circles is to use the center point and a radius, which is for example used when drawing a circle in JavaScript. Using this definition however would not fit with the proposed definition of a _CompoundCurve_ where the first position of the next segment must be equivalent to the last position of the previous segment.

* WKB defines a _CircularString_ which is a compact way of storing 1+ arcs. The proposed _Arc_ geometry type can be adopted to support this, but it would lose the JSON schema validation on the maximum number of items in an _Arc_.

* Used information:
** link:https://datatracker.ietf.org/doc/html/rfc7946[The GeoJSON Format]
** link:https://portal.ogc.org/files/?artifact_id=20509[07-036 GML 3.2.1]
** link:https://portal.ogc.org/files/?artifact_id=829[99-049 OpenGIS Simple Features Specification For SQL Rev 1.1]
** link:https://portal.ogc.org/files/?artifact_id=25355[06-103r4 OpenGIS Implementation Specification for Geographic information - Simple feature access - Part 1: Common architecture]
** link:https://www.iso.org/standard/66175.html[ISO 19107:2019 (Geographic information — Spatial schema)]
** link:https://www.iso.org/standard/60343.html[ISO/IEC 13249-3:2016 (Information technology — Database languages — SQL multimedia and application packages — Part 3: Spatial)]
