= Identifying the feature type(s)

Version: 0.1.0

== Overview

Features are often categorized by type. Typically all features of the same type have the same schema, the same properties.

Many GIS clients depend on knowledge about the feature type when processing feature data, for example, to associate a style to render the feature on a map with the feature.

GeoJSON is schema-less in the sense that it has no concept of feature types or feature schemas.

In most cases, a feature is an instance of a single feature type. The current draft revision of the Simple Features standard supports features that are instances of multiple types. This proposal, therefore, also supports multiple feature types.

The related proposal link:schema-ref.adoc[Identifying the schema] specifies how the JSON Schema documents are identified that the JSON document conforms to. This proposal specifies how to represent feature type information in the JSON object that represents the feature.

== Examples

A feature instance of an AirportHeliport feature type from the Aeronautical Information Exchange Model (AIXM):

.Feature instance with "featureType" member and "type" link
[%collapsible]
====
[source,json]
----
{
   "type":"Feature",
   "featureType":"aixm:AirportHeliport",
   "coordRefSys":"http://www.opengis.net/def/crs/OGC/1.3/CRS84",
   "id":38,
   "geometry":{
      "type":"Point",
      "coordinates":[
         -89.9766666666667,
         35.0424166666667
      ]
   },
   "properties":{
      "airport":"MEM",
      "designator":"KMEM",
      "name":"MEMPHIS INTL",
      "type":"AH"
   },
   "where":null,
   "links":[
      {
        "href":"https://t17.ldproxy.net/airports/collections/airportheliport/items/38?f=jsonfg",
        "rel":"self",
        "type":"application/vnd.ogc.fg+json",
        "title":"This document"
      },
      {
        "href":"https://t17.ldproxy.net/airports/collections/airportheliport/items/38?f=json",
        "rel":"alternate",
        "type":"application/geo+json",
        "title":"This document as GeoJSON"
      },
      {
        "href":"https://t17.ldproxy.net/airports/collections/airportheliport/items/38?f=html",
        "rel":"alternate",
        "type":"text/html",
        "title":"This document as HTML"
      },
      {
        "href":"https://t17.ldproxy.net/airports/collections/airportheliport?f=json",
        "rel":"collection",
        "type":"application/json",
        "title":"The collection the feature belongs to"
      },
      {
        "href":"https://aixm.aero/sites/aixm.aero/files/imce/AIXM511HTML/AIXM/Class_AirportHeliport.html",
        "rel":"type",
        "type":"text/html",
        "title":"Description of the AIXM 5.1 AirportHeliport feature type"
      },
      {
        "href":"https://t17.ldproxy.net/airports/collections/airportheliport/schemas/feature",
        "rel":"describedby",
        "type":"application/schema+json",
        "title":"Schema of features in 'Airport/Heliport'"
      },
      {
        "href":"https://geojson.org/schema/Feature.json",
        "rel":"describedby",
        "type":"application/schema+json",
        "title":"This document is a GeoJSON Feature"
      }
   ]
}
----
====

Note that in the example, the URI that has been used for the semantic type should really be a persistent URI of an entry in some AIXM registry, but no such registry for the AIXM feature types seems to be exist. 

== Description

The feature types of a feature are declared in a top-level member with the key "featureType". The value is either a string (in case of a single feature type) or an array of strings (to support multiple feature types). Each string should be a code, convenient for the use in filter expressions.

If a persistent resource exists, e.g. in a registry, that describes a feature type, a link to that resource with link relation type `type` should be added. In the case of multiple feature types per feature, multiple links are added.

OGC API Features already specifies a general "links" member with an array of link objects based on https://tools.ietf.org/html/rfc8288[RFC 8288 (Web linking)] and feature responses from APIs implementing OGC API Features will already include a "links" member. The proposal is to build on this approach and include a "describedby" link to a JSON Schema document in the "links" array, if schema information is important for the target users of the JSON feature documents. 

.Link properties
[cols="20,10,70",options="header"]
!===
|Property |Type |Description
|href |URI |**REQUIRED**. The URI of a persistent resource that describes a feature type that is instantiated by the feature that is the link context.
|rel |String |**REQUIRED**. The link relation type, always "type".
|type |String |To indicate a hint about a specific media type in which the target of the link is available, set the value to that media type; for example, "text/html".
|title |String |Include this link attribute for a human readable label of the link, e.g. for use in a derived HTML representation.
!===

Additional link attributes may be added to the Link object.

== Discussion, Alternatives, References

1. If JSON-LD is used, the "featureType" member could be mapped to "@type".

2. Should we distinguish between feature types that simply identifies a concept, but has no associated or no well-defined schema, and feature types that have an associated schema (the schema would be linked using a "describedby" link relation type)?
