
= Encoding of reference systems in a JSON-FG document

Version: 0.1.1

== Tl;dr

Without any other information, the following defaults apply in a JSON-FG file:

* coordinate reference system: CRS84 or CRS84h (if there is a vertical dimension)
* vertical reference system: whatever the vertical reference system used for CRS84h is (i.e. meters above the ellipsoid).
* temporal reference system: Gregorian

For asserting CRS information in a JSON-FG file:

* The key <<coord-ref-systems-schema,`coordRefSys`>> is defined and can be used to assert a CRS at the collection, feature or value levels.
* The value of the <<coord-ref-systems-schema,`coordRefSys`>> key can be:
** a <<rs-by-simple-ref,simple URI reference>>,
** a <<rs-by-ref-with-epoch,URI reference>> with an epoch,
** or as an array of CRS references (with or without epoch) for an ad hoc compound CRS.

It is anticipated that if a CRS is asserted for a JSON-FG file, that assertion will be made at the top level of the document; either at the collection level or the feature level depending on the contents of the document.

[#eighty-percent-example,reftext='{listing-caption} {counter:listing-num}']
.Asserting a CRS at the collection level in a JSON-FG file
====
[source,json,linenumbers]
----

{
  "type": "FeatureCollection",
  "numberReturned": 10,
  "numberMatched": 5573,
  "timeStamp": "2021-07-18T23:00:25Z",
  "coordRefSys": "http://www.opengis.net/def/crs/EPSG/0/5555",
  "features": [ 
    .
    .
    .
  ]
}
----
====

== Overview

Spatio-temporal objects are specified relative to some reference system.

GeoJSON (both the current https://tools.ietf.org/html/rfc7946[RFC] and the https://geojson.org/geojson-spec.html[legacy version]) fixed the reference system for geometric values to "WGS84 datum, and with longitude and latitude units of decimal degrees".  The https://geojson.org/geojson-spec.html[legacy version] included a "prior arrangment" provision to allow other reference systems to be used and also defined the `crs` key for specifying the reference system.  This _prior arrangement_ mechanism survived into the https://tools.ietf.org/html/rfc7946[RFC] but the accompanying `crs` key did not.  The result is that there is no interoperable way to unambiguously assert a different CRS if GeoJSON files and the safest thing to do is to stick with CRS84(h) for GeoJSON members and ignore the _prior arragment_ provision and the old `crs` key.

JSON-FG is not bound by these restrictions and so this document outlines a proposal for handling reference systems in JSON-FG documents that does not interfere with anything, past or present, defined in any of the GeoJSON specifications.  The GeoJSON elements can continue to operate as always but JSON-FG elements can avail themselves of enhanced coordinate reference system support.

== Considerations

The following were taken into account in this proposal:

. Reuse GeoJSON CRS mechanism
** **Consideration**: Should we reuse the `crs` mechanism from the https://geojson.org/geojson-spec.html[legacy version of GeoJSON]?
** **Decision**: No. It is tempting to reuse the legacy mechanism because over the years a large number of GeoJSON clients have emerged that can handle the `crs` key and make use of the _prior arrangement_ provision of the https://geojson.org/geojson-spec.html[legacy GeoJSON specification].  However, reusing this mechanism would introduce a significant amount of ambiguity.  It would be unclear whether the presence of the `crs` key was targeting the GeoJSON keys (i.e. geometry) or the JSON-FG keys (i.e. where).  Even though the https://tools.ietf.org/html/rfc7946[GeoJSON RFC] does not define a CRS mechnism, the mere fact that dependencies have been built on the legacy mechanism disqualifies it from being redefined for JSON-FG use.  

. Scope of applicability
** **Consideration**: To which values in a JSON-FG file should the specified reference systems apply?
** **Decision**: The key(s) defined in this proposal only apply to JSON-FG spatio-temporal objects (e.g. `where`, `when`) and any spatio-temporal value in the `properties` section which are not bound by GeoJSON requirements.  So, the herein defined key(s) **don't** apply to any defined GeoJSON spatio-temporal element such as `geometry`.

. Temporal and vertical reference systems.
** **Consideration**: Do we need to handle temporal and vertical reference systems? 
** **Decision**: I would say that 80+% of the use cases are probably for geographic or projected coordinate reference systems and we should focus on correctly tagging those in a JSON-FG document.  However, techincally, temporal and vertical reference systems are just coordinate reference systems too and so the proposed CRS mechanism should handle these as well.

. Coordinate order
** **Consideration**: According to the GeoJSON RFC: "The coordinate reference system for all GeoJSON coordinates is a geographic coordinate reference system, using the World Geodetic System 1984 (WGS 84) [WGS84] datum, with longitude and latitude units of decimal degrees.  This is equivalent to the coordinate reference system identified by the Open Geospatial Consortium (OGC) URN urn:ogc:def:crs:OGC::CRS84.  An OPTIONAL third-position element SHALL be the height in meters above or below the WGS 84 reference ellipsoid.  In the absence of elevation values, applications sensitive to height or depth SHOULD interpret positions as being at local ground or sea level." There is also the _prior agreement_ provision that loosens this requirement if all parties agree.  What shall we do in JSON-FG with regard to coordinate order?
** **Decision**: For JSON-FG spatio-temporal values, the coordinate order -- following OGC policy -- shall be in the order specified by the CRS. PERIOD!

. Scoping rules
** **Consideration**: Do we need to be able to tag reference system information at various levels (i.e. collection level, feature level, value level)?
** **Decision**: Reference system information for JSON-FG spatio-temporal values will primarily be asserted at the top level of a file (collection or feature) since it is likely that all values in a document will be in the same CRS.  However, having defined a structure for asserting reference system information at the top level, it is a fairly simple matter to reuse the key(s) to assert reference system information at deeper levels (i.e. feature-level or value-level).

. Specifying reference system information by value or by reference
** **Consideration**: Do we need to handle specifying reference system information by reference and by value?
** **Decision**: Handling reference systems by reference seems reasonable for JSON-FG core and also aligns with https://docs.ogc.org/is/18-058/18-058.html[Features Part 2]. While being able to specify CRSs by value might be a useful capability, it is unclear that this is something that should be in the core of JSON-FG.  A schema was defined to handle this use case but is specified in the <<value-schema-annex,ANNEX>> of this document until more feedback on the requirement is gathered.

. Compound reference systems
** **Consideration**: Do we need to handle compound reference systems?
** **Decision**: Yes.  A mechanism is defined in this proposal for specifying compound reference systems.

. Dictionary of reference systems
** **Consideration**: Is there a need to specify the reference systems used in a JSON-FG file up-front in a dictionary?
** **Decision**: This capability closely mirrors what is done in https://www.ogc.org/standards/geopackage[GeoPackage] and might be useful for the "offline container" use case of TB17.  However, it is unclear if this is something that should be defined in the core of JSON-FG.  A mechanism was defined to handle this use case but is specified in the <<ref-systems-dictionary,ANNEX>> of this document until more feedback on the requirement is gathered.

. Separate vertical reference system handling
** **Consideration**: Is there a requirement for separate vertical CRS handling?
** **Decision**: Many times the elevation component of data is handled as a separate property rather than being in the geometry.  Such properties are typically defined using a simple type (i.e. double) and so, unlike object values, an additional key conveying reference system information cannot be conveniently and unambiguously added.  While this might be another useful capability, it is unclear that this is something that should be in the core of JSON-FG.  A mechanism was defined to handle this use case but is specified in the <<sc-value-ref-sys,ANNEX>> of this document until more feedback on the requirement is gathered.

== Reference system values

=== Overview

A reference system can be specified in a JSON-FG document in one of three ways:

. as a simple reference using a URI,

. as a simple reference using a URI accompanied by an epoch value,

. as an array of reference system values denoting an ad hoc compound reference system.

=== Value schema

The following JSON Schema fragment defines a reference system value:

[#value-schema,reftext='{listing-caption} {counter:listing-num}']
.The schema of a reference system value
====
[source,json,linenumbers]
----
   {
      "$defs": {
         "refsys-simple-ref": {
            "type": "string",
            "format": "uri"
         },
         "refsys-byref": {
            "type": "object",
            "required": [ "href" ],
            "properties": {
               "href": {
                  "type": "string",
                  "format": "uri"
               },
               "epoch": {
                  "type": "string"
               }
            }
         },
         "refsys": {
            "oneOf": [
               { "$ref": "#/$defs/refsys-simpleref" },
               { "$ref": "#/$defs/refsys-byref" },
               {
                  "type": "array",
                  "items": {
                     "oneOf": [
                        { "$ref": "#/$defs/refsys-simpleref" },
                        { "$ref": "#/$defs/refsys-byref" },
                     ]
                  }
               }
            ]
         }
      },
      "$ref": "#/$defs/refsys"
   }
----
====

[#rs-by-simple-ref,reftext='{listing-caption} {counter:listing-num}']
.A simple reference system value by reference.
====
[source,json,linenumbers]
----
"http://www.opengis.net/def/crs/EPSG/0/3857"
----
====

[#rs-by-ref-with-epoch,reftext='{listing-caption} {counter:listing-num}']
.A reference system value by reference and with an epoch.
====
[source,json,linenumbers]
----
{
  "href": "http://www.opengis.net/def/crs/EPSG/0/3857",
  "epoch": "2016.47"
}
----
====

[#compound-rs-by-value,reftext='{listing-caption} {counter:listing-num}']
.A ad hoc compound reference system value
====
[source,json,linenumbers]
----
[
  {
    "href": "http://www.opengis.net/def/crs/EPSG/0/25832",
    "epoch": "2016.47"
  },
  "http://www.opengis.net/def/crs/EPSG/0/5783"
]
----
====

== Keys

=== Coordinate reference system

The `coordRefSys` key is defined for tagging the coordinate reference system of a JSON-FG spatio-temporal value.

[#coord-ref-systems-schema,reftext='{listing-caption} {counter:listing-num}']
.The schema of the `coordRefSys` key
====
[source,json,linenumbers]
----
{"$ref": "#/$defs/refsys" }
----
====

Used at the collection level, the `coordRefSys` key asserts the coordinate reference system for JSON-FG spatio-temporal values found anywhere in the document that are not otherwise tagged with closer-to-scope coordinate reference system information.

[#collection-level-rs-example,reftext='{listing-caption} {counter:listing-num}']
.An example of assering CRS information at the collection level.
====
[source,json,linenumbers]
----

{
  "type": "FeatureCollection",
  "@context": "https://t17.ldproxy.net/airspace/collections/class_all/context",
  "@type": "geojson:FeatureCollection",
  "numberReturned": 10,
  "numberMatched": 5573,
  "timeStamp": "2021-07-18T23:00:25Z",
  "coordRefSys":  "http://www.opengis.net/...",
  "features": [ ... ]
}
----
====

Used at the feature level, the `coordRefSys` key asserts the coordinate reference system for geometric JSON-FG value found anywhere in the feature that are not otherwise tagged with closer-to-scope coordinate reference system information.

[#feature-level-rs-example,reftext='{listing-caption} {counter:listing-num}']
.Reference system specified at the feature-level.
[%collapsible]
====
[source,json,linenumbers]
----
{
   "type": "Feature",
   "id": "DENW19AL0000giv5BL",
   "coordRefSys": "http://www.opengis.net/def/crs/EPSG/0/5555",
   "geometry": {
      "type": "Polygon",
      "coordinates": [
         [
            [ 8.709204563652449, 51.50352856284526, 100.0 ],
            [ 8.709312860802727, 51.503457005181794, 100.0 ],
            [ 8.709391968693081, 51.50350306810203, 100.0 ],
            [ 8.709283757429898, 51.503574715968284, 100.0 ],
            [ 8.709204563652449, 51.50352856284526, 100.0 ]
         ]
      ]
   },
   "when": [ "2014-04-24T10:50:18Z", null ],
   "where": {
      "type": "Polyhedron",
      "coordinates": [
         [ [ [ 479816.67, 5705861.672, 100 ],
             [ 479824.155, 5705853.684, 100 ],
             [ 479829.666, 5705858.785, 100 ],
             [ 479822.187, 5705866.783, 100 ],
             [ 479816.67, 5705861.672, 100 ] ]
         ],
         [ [ [ 479816.67, 5705861.672, 110 ],
             [ 479824.155, 5705853.684, 110 ],
             [ 479829.666, 5705858.785, 120 ],
             [ 479822.187, 5705866.783, 120 ],
             [ 479816.67, 5705861.672, 110 ] ]
         ],
         [ [ [ 479816.67, 5705861.672, 110 ],
             [ 479824.155, 5705853.684, 110 ],
             [ 479824.155, 5705853.684, 100 ],
             [ 479816.67, 5705861.672, 100 ],
             [ 479816.67, 5705861.672, 110 ] ]
         ],
         [ [ [ 479824.155, 5705853.684, 110 ],
             [ 479829.666, 5705858.785, 120 ],
             [ 479829.666, 5705858.785, 100 ],
             [ 479824.155, 5705853.684, 100 ],
             [ 479824.155, 5705853.684, 110 ] ]
         ],
         [ [ [ 479829.666, 5705858.785, 120 ],
             [ 479822.187, 5705866.783, 120 ],
             [ 479822.187, 5705866.783, 100 ],
             [ 479829.666, 5705858.785, 100 ],
             [ 479829.666, 5705858.785, 120 ] ]
         ],
         [ [ [ 479822.187, 5705866.783, 120 ],
             [ 479816.67, 5705861.672, 110 ],
             [ 479816.67, 5705861.672, 100 ],
             [ 479822.187, 5705866.783, 100 ],
             [ 479822.187, 5705866.783, 120 ] ]
         ]
      ]
   },
   "properties": {
      "lastChange": "2014-04-24T10:50:18Z",
      "function": "Agricultural building",
      "height_m": 20.0
   }
}
----
====

Used at the value level, the `coordRefSys` key asserts the coordinate reference system for the geometry JSON-FG value within which the key is contained.

[#value-level-rs-example,reftext='{listing-caption} {counter:listing-num}']
.Reference system specified at the value-level.
[%collapsible]
====
[source,json,linenumbers]
----
{
   "type": "Feature",
   "id": "DENW19AL0000giv5BL",
   "geometry": {
      "type": "Polygon",
      "coordinates": [
         [
            [ 8.709204563652449, 51.50352856284526, 100.0 ],
            [ 8.709312860802727, 51.503457005181794, 100.0 ],
            [ 8.709391968693081, 51.50350306810203, 100.0 ],
            [ 8.709283757429898, 51.503574715968284, 100.0 ],
            [ 8.709204563652449, 51.50352856284526, 100.0 ]
         ]
      ]
   },
   "when": [ "2014-04-24T10:50:18Z", null ],
   "where": {
      "type": "Polyhedron",
      "coordRefSys": "http://www.opengis.net/def/crs/EPSG/0/5555",
      "coordinates": [
         [ [ [ 479816.67, 5705861.672, 100 ],
             [ 479824.155, 5705853.684, 100 ],
             [ 479829.666, 5705858.785, 100 ],
             [ 479822.187, 5705866.783, 100 ],
             [ 479816.67, 5705861.672, 100 ] ]
         ],
         [ [ [ 479816.67, 5705861.672, 110 ],
             [ 479824.155, 5705853.684, 110 ],
             [ 479829.666, 5705858.785, 120 ],
             [ 479822.187, 5705866.783, 120 ],
             [ 479816.67, 5705861.672, 110 ] ]
         ],
         [ [ [ 479816.67, 5705861.672, 110 ],
             [ 479824.155, 5705853.684, 110 ],
             [ 479824.155, 5705853.684, 100 ],
             [ 479816.67, 5705861.672, 100 ],
             [ 479816.67, 5705861.672, 110 ] ]
         ],
         [ [ [ 479824.155, 5705853.684, 110 ],
             [ 479829.666, 5705858.785, 120 ],
             [ 479829.666, 5705858.785, 100 ],
             [ 479824.155, 5705853.684, 100 ],
             [ 479824.155, 5705853.684, 110 ] ]
         ],
         [ [ [ 479829.666, 5705858.785, 120 ],
             [ 479822.187, 5705866.783, 120 ],
             [ 479822.187, 5705866.783, 100 ],
             [ 479829.666, 5705858.785, 100 ],
             [ 479829.666, 5705858.785, 120 ] ]
         ],
         [ [ [ 479822.187, 5705866.783, 120 ],
             [ 479816.67, 5705861.672, 110 ],
             [ 479816.67, 5705861.672, 100 ],
             [ 479822.187, 5705866.783, 100 ],
             [ 479822.187, 5705866.783, 120 ] ]
         ]
      ]
   },
   "properties": {
      "lastChange": "2014-04-24T10:50:18Z",
      "function": "Agricultural building",
      "height_m": 20.0
   }
}
----
====

[[annex]]
== ANNEX - Deprecated or "awaiting more feedback" items

=== Overview

This section contains content that was originally in the main body of this proposal but, upon review, was deemed unneccessary for the JSON-FG core by the SWG.  If, with additional feedback, any of this content is deemed as being suitable for the core, it can be moved back into the body of this proposal and ultimately included the JSON-FG specification.

=== Tl;dr

* Reference system values can be specified as:
** by <<rs-by-value-proj,value>>
* The <<sc-value-ref-sys,`value-ref-sys`>> key defines a lookup table that allows reference systems to be asserted for simple JSON-FG values.  Unlike object values, additional properties (i.e. `coordRefSys`) cannot be added to simple values to assert a reference system.
* The <<ref-systems-dictionary,`ref-systems`>> key can be used to declare, at the collection level, a dictionary of reference systems used in the document.  Values from this dictionary can be referenced within the document using the aforementioned <<coord-ref-systems-schema,`coordRefSys`>> key and relative URL references/JSON pointer values.

[[value-schema-annex]]
=== Reference system values

==== Overview

A reference system can be specified in a JSON-FG document in one for four ways:

. by value using any well known encoding such as PROJJSON or OGCWKT.  Other encodings are allowed (e.g. GML CRS) but not discussed in this proposal.

==== Value schema

The following JSON Schema fragment defines a reference system value:

[reftext='{listing-caption} {counter:listing-num}']
.The schema of a reference system value
====
[source,json,linenumbers]
----
   {
      "$defs": {
         "refsys-simple-ref": {
            "type": "string",
            "format": "uri"
         },
         "refsys-byref": {
            "type": "object",
            "required": [ "href" ],
            "properties": {
               "href": {
                  "type": "string",
                  "format": "uri"
               },
               "epoch": {
                  "type": "string"
            }
            }
         },
         "refsys-byvalue": {
            "type": "object",
            "required": [ "valueType", "value" ],
            "properties": {
               "valueType": {
                  "type": "string",
                  "enum": ["projjson","ogcwkt"]
               },
               "value": {
                  "oneOf": [
                     { "type": "string" },
                     { "type": "object" },
                  ]
               },
               "epoch": {
                  "type": "string"
               }
            }
         },
         "refsys": {
            "oneOf": [
               { "$ref": "#/$defs/refsys-simpleref" },
               { "$ref": "#/$defs/refsys-byref" },
               { "$ref": "#/$defs/refsys-byvalue" },
               {
                  "type": "array",
                  "items": {
                     "oneOf": [
                        { "$ref": "#/$defs/refsys-simpleref" },
                        { "$ref": "#/$defs/refsys-byref" },
                        { "$ref": "#/$defs/refsys-byvalue" },
                     ]
                  }
               }
            ]
         }
      },
      "$ref": "#/$defs/refsys"
   }
----
====

[#vertical-rs-by-value,reftext='{listing-caption} {counter:listing-num}']
.An vertical reference system value specified by value using OGC WKT notation.
====
[source,json,linenumbers]
----
{
  "valueType": "ogcwkt",
  "value": "VERTCRS[\"NAVD88\", VDATUM[\"North American Vertical Datum 1988\"], CS[vertical,1], AXIS[\"gravity-related height (H)\",up], LENGTHUNIT[\"metre\",1.0]]"
}
----
====

[#temporal-rs-by-value,reftext='{listing-caption} {counter:listing-num}']
.A temporal reference system value specified by value using PROJ JSON notation.
====
[source,json,linenumbers]
----
{
  "valueType": "projjson",
  "value": {
    "type": "TemporalCRS",
    "name": "Gregorian",
    "datum": {
      "type": "TemporalDatum",
      "name": "Gregorian",
      "calendar": "Gregorian"
    }
  }
}
----
====

[#coordinate-rs-by-value-wkt,reftext='{listing-caption} {counter:listing-num}']
.A coordinate reference system value specified by value using OGC WKT notation.
====
[source,json,linenumbers]
----
{
  "valueType": "ogcwkt",
  "value": "PROJCRS[\"NAD27 / Texas South Central\", BASEGEOGCRS[\"NAD27\", DATUM[\"North American Datum 1927\", ELLIPSOID[\"Clarke 1866\",20925832.164,294.97869821, LENGTHUNIT[\"US survey foot\",0.304800609601219]] ] ], CONVERSION[\"Texas South Central SPCS27\", METHOD[\"Lambert Conic Conformal (2SP)\",ID[\"EPSG\",9802]], PARAMETER[\"Latitude of false origin\",27.83333333333333, ANGLEUNIT[\"degree\",0.0174532925199433],ID[\"EPSG\",8821]], PARAMETER[\"Longitude of false origin\",-99.0, ANGLEUNIT[\"degree\",0.0174532925199433],ID[\"EPSG\",8822]], PARAMETER[\"Latitude of 1st standard parallel\",28.383333333333, ANGLEUNIT[\"degree\",0.0174532925199433],ID[\"EPSG\",8823]], PARAMETER[\"Latitude of 2nd standard parallel\",30.283333333333, ANGLEUNIT[\"degree\",0.0174532925199433],ID[\"EPSG\",8824]], PARAMETER[\"Easting at false origin\",2000000.0, LENGTHUNIT[\"US survey foot\",0.304800609601219],ID[\"EPSG\",8826]], PARAMETER[\"Northing at false origin\",0.0, LENGTHUNIT[\"US survey foot\",0.304800609601219],ID[\"EPSG\",8827]] ], CS[Cartesian,2], AXIS[\"(X)\",east], AXIS[\"(Y)\",north], LENGTHUNIT[\"US survey foot\",0.304800609601219], REMARK[\"Fundamental point: Meade's Ranch KS, latitude 39째13'26.686\"\"N, longitude 98째32'30.506\"\"W.\"] ]"
}
----
====

[#rs-by-value-proj,reftext='{listing-caption} {counter:listing-num}']
.A coordinate reference system value specified by value using PROJ JSON notation.
[%collapsible]
====
[source,json,linenumbers]
----
{
  "valueType": "projjson",
  "value": {
    "$schema": "https://proj.org/schemas/v0.1/projjson.schema.json",
    "type": "ProjectedCRS",
    "name": "WGS 84 / UTM zone 31N",
    "base_crs": {
      "name": "WGS 84",
      "datum": {
        "type": "GeodeticReferenceFrame",
        "name": "World Geodetic System 1984",
        "ellipsoid": {
          "name": "WGS 84",
          "semi_major_axis": 6378137,
          "inverse_flattening": 298.257223563
        }
      },
      "coordinate_system": {
        "subtype": "ellipsoidal",
        "axis": [
          {
            "name": "Geodetic latitude",
            "abbreviation": "Lat",
            "direction": "north",
            "unit": "degree"
          },
          {
            "name": "Geodetic longitude",
            "abbreviation": "Lon",
            "direction": "east",
            "unit": "degree"
          }
        ]
      },
      "id": {
        "authority": "EPSG",
        "code": 4326
      }
    },
    "conversion": {
      "name": "UTM zone 31N",
      "method": {
        "name": "Transverse Mercator",
        "id": {
          "authority": "EPSG",
          "code": 9807
        }
      },
      "parameters": [
        {
          "name": "Latitude of natural origin",
          "value": 0,
          "unit": "degree",
          "id": {
            "authority": "EPSG",
            "code": 8801
          }
        },
        {
          "name": "Longitude of natural origin",
          "value": 3,
          "unit": "degree",
          "id": {
            "authority": "EPSG",
            "code": 8802
          }
        },
        {
          "name": "Scale factor at natural origin",
          "value": 0.9996,
          "unit": "unity",
          "id": {
            "authority": "EPSG",
            "code": 8805
          }
        },
        {
          "name": "False easting",
          "value": 500000,
          "unit": "metre",
          "id": {
            "authority": "EPSG",
            "code": 8806
          }
        },
        {
          "name": "False northing",
          "value": 0,
          "unit": "metre",
          "id": {
            "authority": "EPSG",
            "code": 8807
          }
        }
      ]
    },
    "coordinate_system": {
      "subtype": "Cartesian",
      "axis": [
        {
          "name": "Easting",
          "abbreviation": "E",
          "direction": "east",
          "unit": "metre"
        },
        {
          "name": "Northing",
          "abbreviation": "N",
          "direction": "north",
          "unit": "metre"
        }
      ]
    },
    "area": "World - N hemisphere - 0째E to 6째E - by country",
    "bbox": {
      "south_latitude": 0,
      "west_longitude": 0,
      "north_latitude": 84,
      "east_longitude": 6
    },
    "id": {
      "authority": "EPSG",
      "code": 32631
    }
  }
}
----
====

[#compound-rs-by-value-ref,reftext='{listing-caption} {counter:listing-num}']
.A compound reference system value specified by reference and value.
====
[source,json,linenumbers]
----
[
  "http://www.opengis.net/def/crs/EPSG/0/25832",
  {
    "valueType": "ogcwkt",
    "VERTCRS[\"DHHN92 height\",VDATUM[\"Deutsches Haupthoehennetz 1992\",ID[\"EPSG\",5181]],CS[vertical,1,ID[\"EPSG\",6499]],AXIS[\"Gravity-related height (H)\",up],LENGTHUNIT[\"metre\",1,ID[\"EPSG\",9001]],ID[\"EPSG\",5783]]"
  }
]
----
====

=== Keys

[[ref-systems-dictionary]]
==== Reference systems dictionary

The `ref-systems` key is defined for specifying a dictionary of reference systems used in a JSON-FG document.  The following schema fragment defines the schema of the `ref-systems` key:

[#ref-systems-schema,reftext='{listing-caption} {counter:listing-num}']
.The schema of the `ref-systems` key
====
[source,json,linenumbers]
----
{
   "type": "object",
   "patternProperties": {
      ".*": { "$ref": "#/$defs/refsys" },
   }
}
----
====

Values for the dictionary can be referenced in the rest of the document using the appropriate key (i.e. `coordRefSys`) with a relative URL/JSON pointer referencing a value from the dictionary.

[#rs-dictionary-example,reftext='{listing-caption} {counter:listing-num}']
.An example of a dictionary of reference systems.
====
[source,json,linenumbers]
----
{
  "type": "FeatureCollection",
  "numberReturned": 10,
  "numberMatched": 5573,
  "timeStamp": "2021-07-18T23:00:25Z",
  "ref-systems": {
    "25832": {
      "valueType": "ogcwkt",
      "value": "PROJCRS[\"ETRS89 / UTM zone 32N\",BASEGEOGCRS[\"ETRS89\",ENSEMBLE[\"European Terrestrial Reference System 1989 ensemble\", MEMBER[\"European Terrestrial Reference Frame 1989\", ID[\"EPSG\",1178]], MEMBER[\"European Terrestrial Reference Frame 1990\", ID[\"EPSG\",1179]], MEMBER[\"European Terrestrial Reference Frame 1991\", ID[\"EPSG\",1180]], MEMBER[\"European Terrestrial Reference Frame 1992\", ID[\"EPSG\",1181]], MEMBER[\"European Terrestrial Reference Frame 1993\", ID[\"EPSG\",1182]], MEMBER[\"European Terrestrial Reference Frame 1994\", ID[\"EPSG\",1183]], MEMBER[\"European Terrestrial Reference Frame 1996\", ID[\"EPSG\",1184]], MEMBER[\"European Terrestrial Reference Frame 1997\", ID[\"EPSG\",1185]], MEMBER[\"European Terrestrial Reference Frame 2000\", ID[\"EPSG\",1186]], MEMBER[\"European Terrestrial Reference Frame 2005\", ID[\"EPSG\",1204]], MEMBER[\"European Terrestrial Reference Frame 2014\", ID[\"EPSG\",1206]], ELLIPSOID[\"GRS 1980\",6378137,298.2572221,LENGTHUNIT[\"metre\",1,ID[\"EPSG\",9001]],ID[\"EPSG\",7019]], ENSEMBLEACCURACY[0.1],ID[\"EPSG\",6258]],ID[\"EPSG\",4258]],CONVERSION[\"UTM zone 32N\",METHOD[\"Transverse Mercator\",ID[\"EPSG\",9807]],PARAMETER[\"Latitude of natural origin\",0,ANGLEUNIT[\"degree\",0.0174532925199433,ID[\"EPSG\",9102]]],PARAMETER[\"Longitude of natural origin\",9,ANGLEUNIT[\"degree\",0.0174532925199433,ID[\"EPSG\",9102]]],PARAMETER[\"Scale factor at natural origin\",0.9996,SCALEUNIT[\"unity\",1,ID[\"EPSG\",9201]]],PARAMETER[\"False easting\",500000,LENGTHUNIT[\"metre\",1,ID[\"EPSG\",9001]]],PARAMETER[\"False northing\",0,LENGTHUNIT[\"metre\",1,ID[\"EPSG\",9001]]],ID[\"EPSG\",16032]],CS[Cartesian,2,ID[\"EPSG\",4400]],AXIS[\"Easting (E)\",east],AXIS[\"Northing (N)\",north],LENGTHUNIT[\"metre\",1,ID[\"EPSG\",9001]],ID[\"EPSG\",25832]]"
    },
    "5783": {
      "valueType": "ogcwkt",
      "value": "VERTCRS[\"DHHN92 height\",VDATUM[\"Deutsches Haupthoehennetz 1992\",ID[\"EPSG\",5181]],CS[vertical,1,ID[\"EPSG\",6499]],AXIS[\"Gravity-related height (H)\",up],LENGTHUNIT[\"metre\",1,ID[\"EPSG\",9001]],ID[\"EPSG\",5783]]"
    }
  },
  "coordRefSys":  [
    { "href": "#/ref-systems/25832" },
    { "href": "#/ref-systems/5783" }
  ]
  "features": [ ... ]
}
----
====

[[sc-value-ref-sys]]
==== Reference systems for simple JSON-FG values

It is a simple matter to assert a reference system for structured JSON-FG values such as `where` because additional properties can be added to the structure that convey the reference system information.  For simple JSON-FG values (e.g. `height` defined as a `double`) this is not possible.  Consider the following example:

[#height-example,reftext='{listing-caption} {counter:listing-num}']
.A simple height property without a reference system.
====
[source,json,linenumbers]
----
{
   "type": "Feature",
   "id": "DENW19AL0000giv5BL",
   "coordRefSys": "http://www.opengis.net/def/crs/EPSG/0/5555",
   "geometry": {
      "type": "Polygon",
      "coordinates": [ ... ]
   },
   "when": [ "2014-04-24T10:50:18Z", null ],
   "where": {
      "type": "Polyhedron",
      "coordinates": [ ... ]
   },
   "properties": {
      "lastChange": "2014-04-24T10:50:18Z",
      "function": "Agricultural building",
      "height": 20.0
   }
}
----
====

In this example the `height` property does not have a reference system associated with it and asserting one would be awkward since this is a value without strcuture.

The `value-ref-sys` key is defined for asserting a reference system for simple, unstructured, JSON-FG values with the following schema:

[#value-ref-sys,reftext='{listing-caption} {counter:listing-num}']
.The schema of the `value-ref-sys` key
====
[source,json,linenumbers]
----
{
   "type": "object",
   "patternProperties": {
      ".*": { "$ref": "#/$defs/refsys" },
   }
}
----

NOTE: The key values for this object are meant to be https://github.com/json-path/JsonPath[JSON path] expressions so I will need to find a regex for that and update this schema accordingly.
====

Used at the collection level, each key of the `value-ref-sys` object is a JSON pointer to a value in the document.  The value of the key asserts the reference system for the referenced value.

[#height-example-with-rs,reftext='{listing-caption} {counter:listing-num}']
.A simple height property with a reference system.
====
[source,json,linenumbers]
----
{
   "type": "Feature",
   "id": "DENW19AL0000giv5BL",
   "coordRefSys": "http://www.opengis.net/def/crs/EPSG/0/5555",
   "value-ref-sys": {
      "$.properties.height": {
          "valueType": "ogcwkt",
          "value": "VERTCRS[ ... ]"
      }
   },
   "geometry": {
      "type": "Polygon",
      "coordinates": [ ... ]
   },
   "when": [ "2014-04-24T10:50:18Z", null ],
   "where": {
      "type": "Polyhedron",
      "coordinates": [ ... ]
   },
   "properties": {
      "lastChange": "2014-04-24T10:50:18Z",
      "function": "Agricultural building",
      "height": 20.0
   }
}
----
====
