= Encoding a spatial geometry

Version: 0.1.0

== Overview

Features typically have a spatial geometry that provides information about the location of the feature. 

In GeoJSON, this information is encoded in the top-level "geometry" member. Supported are geometries according to the Simple Features standard (2D or 2.5D points, line strings, polygons or aggregations of them) in WGS 84 as the coordinate reference system (OGC:CRS84 or OGC:CRS84h).

It is a key motivation for JSON-FG to support additional requirements, including other coordinate reference systems as well as solids, where the boundary is specified using polygons.

To avoid confusing GeoJSON readers, such geometries will be provided in a new top-level member with the key "where" (or another key).

== Examples

The following example is a valid GeoJSON feature and includes a polygon geometry in WGS 84 long/lat/height (the building footprint), an id and a properties object.

[#example_building_geojson,reftext='{listing-caption} {counter:listing-num}']
.Building with a polygon geometry (footprint) in WGS 84
[%collapsible]
====
[source,json,linenumbers]
----
{
   "type": "Feature",
   "id": "DENW19AL0000giv5BL",
   "geometry": {
      "type": "Polygon",
      "coordinates": [
         [
            [
               8.709204563652449,
               51.50352856284526,
               100.0
            ],
            [
               8.709312860802727,
               51.503457005181794,
               100.0
            ],
            [
               8.709391968693081,
               51.50350306810203,
               100.0
            ],
            [
               8.709283757429898,
               51.503574715968284,
               100.0
            ],
            [
               8.709204563652449,
               51.50352856284526,
               100.0
            ]
         ]
      ]
   },
   "properties": {
      "lastChange": "2014-04-24T10:50:18Z",
      "function": "Agricultural building",
      "height_m": 20.0
   }
}
----
====

The next example is the same building feature as in <<example_building_geojson>>, but the geometry is a solid in the EPSG CRS with code 5555 (ETRS89/UTM zone 32N with height). The geometry is on the JSON-FG member "where" and the coordinate reference system is declared using the "coord-ref-sys" member from the [reference systems proposal](ref-sys.adoc).

The example also includes a "when" member to express the default temporal extent (an open interval).

The feature is still a valid GeoJSON feature, but without information about the location.

[#example_building_jsonfg,reftext='{listing-caption} {counter:listing-num}']
.Building with a polyhedron geometry
[%collapsible]
====
[source,json,linenumbers]
----
{
   "type": "Feature",
   "id": "DENW19AL0000giv5BL",
   "coord-ref-sys": "http://www.opengis.net/def/crs/EPSG/0/5555",
   "geometry": null,
   "when": { 
      "interval": [ "2014-04-24T10:50:18Z", null ]
   },
   "where": {
      "type": "Polyhedron",
      "coordinates": [
         [
            [
               [
                  479816.67,
                  5705861.672,
                  100
               ],
               [
                  479824.155,
                  5705853.684,
                  100
               ],
               [
                  479829.666,
                  5705858.785,
                  100
               ],
               [
                  479822.187,
                  5705866.783,
                  100
               ],
               [
                  479816.67,
                  5705861.672,
                  100
               ]
            ]
         ],
         [
            [
               [
                  479816.67,
                  5705861.672,
                  110
               ],
               [
                  479824.155,
                  5705853.684,
                  110
               ],
               [
                  479829.666,
                  5705858.785,
                  120
               ],
               [
                  479822.187,
                  5705866.783,
                  120
               ],
               [
                  479816.67,
                  5705861.672,
                  110
               ]
            ]
         ],
         [
            [
               [
                  479816.67,
                  5705861.672,
                  110
               ],
               [
                  479824.155,
                  5705853.684,
                  110
               ],
               [
                  479824.155,
                  5705853.684,
                  100
               ],
               [
                  479816.67,
                  5705861.672,
                  100
               ],
               [
                  479816.67,
                  5705861.672,
                  110
               ]
            ]
         ],
         [
            [
               [
                  479824.155,
                  5705853.684,
                  110
               ],
               [
                  479829.666,
                  5705858.785,
                  120
               ],
               [
                  479829.666,
                  5705858.785,
                  100
               ],
               [
                  479824.155,
                  5705853.684,
                  100
               ],
               [
                  479824.155,
                  5705853.684,
                  110
               ]
            ]
         ],
         [
            [
               [
                  479829.666,
                  5705858.785,
                  120
               ],
               [
                  479822.187,
                  5705866.783,
                  120
               ],
               [
                  479822.187,
                  5705866.783,
                  100
               ],
               [
                  479829.666,
                  5705858.785,
                  100
               ],
               [
                  479829.666,
                  5705858.785,
                  120
               ]
            ]
         ],
         [
            [
               [
                  479822.187,
                  5705866.783,
                  120
               ],
               [
                  479816.67,
                  5705861.672,
                  110
               ],
               [
                  479816.67,
                  5705861.672,
                  100
               ],
               [
                  479822.187,
                  5705866.783,
                  100
               ],
               [
                  479822.187,
                  5705866.783,
                  120
               ]
            ]
         ]
      ]
   },
   "properties": {
      "lastChange": "2014-04-24T10:50:18Z",
      "function": "Agricultural building",
      "height_m": 20.0
   }
}
----
====

The next example combines the information from both examples above.

The feature is a valid GeoJSON feature and includes a polygon geometry in WGS 84 long/lat/height (the building footprint), an id and a properties object.

It also includes encodes proposed JSON-FG capabilities that go beyond the scope of GeoJSON ("where" and "when" members).

[#example_building_combined,reftext='{listing-caption} {counter:listing-num}']
.Building with a polyhedron geometry and the polygon footprint
[%collapsible]
====
[source,json,linenumbers]
----
{
   "type": "Feature",
   "id": "DENW19AL0000giv5BL",
   "coord-ref-sys": "http://www.opengis.net/def/crs/EPSG/0/5555",
   "geometry": {
      "type": "Polygon",
      "coordinates": [
         [
            [
               8.709204563652449,
               51.50352856284526,
               100.0
            ],
            [
               8.709312860802727,
               51.503457005181794,
               100.0
            ],
            [
               8.709391968693081,
               51.50350306810203,
               100.0
            ],
            [
               8.709283757429898,
               51.503574715968284,
               100.0
            ],
            [
               8.709204563652449,
               51.50352856284526,
               100.0
            ]
         ]
      ]
   },
   "when": { 
      "interval": [ "2014-04-24T10:50:18Z", null ]
   },
   "where": {
      "type": "Polyhedron",
      "coordinates": [
         [
            [
               [
                  479816.67,
                  5705861.672,
                  100
               ],
               [
                  479824.155,
                  5705853.684,
                  100
               ],
               [
                  479829.666,
                  5705858.785,
                  100
               ],
               [
                  479822.187,
                  5705866.783,
                  100
               ],
               [
                  479816.67,
                  5705861.672,
                  100
               ]
            ]
         ],
         [
            [
               [
                  479816.67,
                  5705861.672,
                  110
               ],
               [
                  479824.155,
                  5705853.684,
                  110
               ],
               [
                  479829.666,
                  5705858.785,
                  120
               ],
               [
                  479822.187,
                  5705866.783,
                  120
               ],
               [
                  479816.67,
                  5705861.672,
                  110
               ]
            ]
         ],
         [
            [
               [
                  479816.67,
                  5705861.672,
                  110
               ],
               [
                  479824.155,
                  5705853.684,
                  110
               ],
               [
                  479824.155,
                  5705853.684,
                  100
               ],
               [
                  479816.67,
                  5705861.672,
                  100
               ],
               [
                  479816.67,
                  5705861.672,
                  110
               ]
            ]
         ],
         [
            [
               [
                  479824.155,
                  5705853.684,
                  110
               ],
               [
                  479829.666,
                  5705858.785,
                  120
               ],
               [
                  479829.666,
                  5705858.785,
                  100
               ],
               [
                  479824.155,
                  5705853.684,
                  100
               ],
               [
                  479824.155,
                  5705853.684,
                  110
               ]
            ]
         ],
         [
            [
               [
                  479829.666,
                  5705858.785,
                  120
               ],
               [
                  479822.187,
                  5705866.783,
                  120
               ],
               [
                  479822.187,
                  5705866.783,
                  100
               ],
               [
                  479829.666,
                  5705858.785,
                  100
               ],
               [
                  479829.666,
                  5705858.785,
                  120
               ]
            ]
         ],
         [
            [
               [
                  479822.187,
                  5705866.783,
                  120
               ],
               [
                  479816.67,
                  5705861.672,
                  110
               ],
               [
                  479816.67,
                  5705861.672,
                  100
               ],
               [
                  479822.187,
                  5705866.783,
                  100
               ],
               [
                  479822.187,
                  5705866.783,
                  120
               ]
            ]
         ]
      ]
   },
   "properties": {
      "lastChange": "2014-04-24T10:50:18Z",
      "function": "Agricultural building",
      "height_m": 20.0
   }
}
----
====

== Description

The main spatial location of a feature is provided in the "geometry" and "where" members of the feature object. The value of both keys is an object representing a spatial geometry - or `null`.

The value of the "geometry" member is specified in the GeoJSON standard.

The value range of the "where" member is an extended and extensible version of the value range of the value range of the "geometry" member:

* It is extended by the value options (additional JSON-FG geometry types <<Polyhedron>> and <<MultiPolyhedron>>) as well as by the capabilities to declare the coordinate reference system of the coordinates of the geometry (#TODO: add link once the proposal is available#).
* It is extensible and future parts of Features and Geometries JSON or community extensions may specify additional members or additional geometry types. JSON-FG readers should be prepared to parse values of "where" that go beyond the schema that is implemented by the reader. Unknown members should be ignored and geometries that include an unknown geometry type should be mapped to `null`.

=== Use of "geometry" and/or "where"

If the geometry that describes the main geometry of the feature can be represented as a valid GeoJSON geometry (one of the GeoJSON geometry types, in WGS84), it is encoded as the value of the "geometry" member. The "where" member has the value `null`.

If the geometry cannot be represented as a valid GeoJSON geometry, it is encoded as the value of the "where" member. In addition, a valid GeoJSON geometry may be provided in the "geometry" member in the coordinate reference system WGS84 as specified in the GeoJSON standard (otherwise "geometry" is set to `null`). The geometry in "geometry" is a fallback for readers that support GeoJSON, but not JSON-FG. This could be a simplified geometry, like the building footprint in <<example_building>> instead of the solid geometry or the same point/line string/polygon geometry, but in WGS 84 (potentially with less vertices to reduce the file size).

=== Polyhedron

A _polyhedron_ is an non-empty array of _multi-polygon_ arrays. Each _multi-polygon_ array is a shell and must be closed. The first shell is the exterior boundary, all other shells are holes.

[#jsonschema_polyhedron,reftext='{listing-caption} {counter:listing-num}']
.JSON Schema for a polyhedron geometry
[%collapsible]
====
[source,json,linenumbers]
----
{
  "$schema": "https://json-schema.org/draft/2019-09/schema",
  "$id": "http://www.opengis.net/tbd/Polyhedron.json",
  "title": "A polyhedron geometry",
  "type": "object",
  "required": [
    "type",
    "coordinates"
  ],
  "properties": {
    "type": {
      "type": "string",
      "enum": [
        "Polyhedron"
      ]
    },
    "coordinates": {
      "type": "array",
      "minItems": 1,
      "items": {
        "type": "array",
        "minItems": 1,
        "items": {
          "type": "array",
          "minItems": 1,
          "items": {
            "type": "array",
            "minItems": 4,
            "items": {
              "type": "array",
              "minItems": 3,
              "maxItems": 3,
              "items": {
                "type": "number"
              }
            }
          }
        }
      }
    },
    "bbox": {
      "type": "array",
      "minItems": 6,
      "maxItems": 6,
      "items": {
        "type": "number"
      }
    }
  }
}
----
====

=== MultiPolyhedron

A _multi-polyhedron_ is an array of _polyhedron_ arrays. The order of the polyhedra is not significant.

[#jsonschema_multipolyhedron,reftext='{listing-caption} {counter:listing-num}']
.JSON Schema for a multi-polyhedron geometry
[%collapsible]
====
[source,json,linenumbers]
----
{
  "$schema": "https://json-schema.org/draft/2019-09/schema",
  "$id": "http://www.opengis.net/tbd/MultiPolyhedron.json",
  "title": "A multi-polyhedron geometry",
  "type": "object",
  "required": [
    "type",
    "coordinates"
  ],
  "properties": {
    "type": {
      "type": "string",
      "enum": [
        "MultiPolyhedron"
      ]
    },
    "coordinates": {
      "type": "array",
      "items": {
        "type": "array",
        "minItems": 1,
        "items": {
          "type": "array",
          "minItems": 1,
          "items": {
            "type": "array",
            "minItems": 1,
            "items": {
              "type": "array",
              "minItems": 4,
              "items": {
                "type": "array",
                "minItems": 3,
                "maxItems": 3,
                "items": {
                  "type": "number"
                }
              }
            }
          }
        }
      }
    },
    "bbox": {
      "type": "array",
      "minItems": 6,
      "maxItems": 6,
      "items": {
        "type": "number"
      }
    }
  }
}
----
====

== Discussion, Alternatives, References

* Does it make sense in JSON-FG to set "where" to `null` and use "geometry" instead, if the geometry is a valid GeoJSON geometry? Or would it be easier to always use "where" for the geometry?

* Should we also add a 3D geometry that represents a simple solid constructed using an extruded polygon? It would consist of a (horizontal) 2D polygon and separate attributes for the lower and upper limits. How often are such geometries used?
